# ------------------------------------------------------
# AEO 2021 Reference Case Commercial Energy End Use Growth Factors Dimensions
# ------------------------------------------------------
# [[dimensions]] # already exists
# type = "geography"
# name = "US-Census-Divisions"
# file = "dimensions/us_census_divisions.csv"
# module = "dsgrid.dimension.standard"
# class = "CensusDivision"
# description = """
# US Census Divisions (N=9)
# """

# [[dimensions]] # already exists
# type = "sector"
# name = "Benchmark-commercial-sector"
# file = "dimensions/sector_commercial.csv"
# module = "dsgrid.dimension.standard"
# class = "Sector"
# description = """
# Benchmark Commercial Sector
# """

[[dimensions]]
type = "subsector"
name = "AEO2021-commercial-building-types"
file = "dimensions/aeo2021_commercial_building_types.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = """
AEO 2021 commercial building types (N=11)
"""

[[dimensions]]
type = "metric"
name = "AEO2021-commercial-energy-enduses-unitless"
file = "dimensions/aeo2021_commercial_energy_enduses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
AEO 2021 commercial energy end uses (unitless) for growth rates (N=19, from 10 end uses, 3 fuel types)
"""

# [[dimensions]] # see if needed
# type = "scenario"
# name = "AEO-Reference-Scenario"
# file = "dimensions/aeo_reference_scenario.csv"
# module = "dsgrid.dimension.standard"
# class = "Scenario"
# description = """
# EIA AEO Reference Scenario
# """

[[dimensions]]
type = "data_source"
name = "Data-Source-AEO-2021"
file = "dimensions/aeo2021_data_source.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = """
EIA Annual Energy Outlook (AEO) 2021
"""

# [[dimensions]] # already exists
# type = "weather_year"
# name = "Weather_Years-trivial-2013_to_2050"
# file = "dimensions/weather_years_trivial_2013_to_2050.csv"
# module = "dsgrid.dimension.standard"
# class = "WeatherYear"
# description = """
# Weather years, 2013-2050, trivial, single record
# """

# [[dimensions]] # already exists
# type = "model_year"
# name = "Model_Years-trivial-2013_to_2050"
# file = "dimensions/model_years_trivial_2013_to_2050.csv"
# module = "dsgrid.dimension.standard"
# class = "ModelYear"
# description = """
# Model years, 2013-2050, trivial, single record
# """

[[dimensions]]
type = "time"
class = "AnnualTime"
time_type = "annual"
description = """Annual time trival"""
module = "dsgrid.dimension.standard"
name = "Annual-Time-Trivial"
measurement_type = "total"
include_leap_day = "true"
