data_source = "aeo2018_reference"
dataset_id = "aeo2018_ref_comm_build_shell_heat_cool_index"
dataset_type = "benchmark"
description = """
commercial building shell heating and cooling factors from 2013-2050 by construction type
"""
path = """
s3://nrel-dsgrid-registry/data/benchmark/aeo2018_reference/
commercial_building_shell_heating_cooling_index/1.0.0"
"""
[[dimensions]]
dimension_id = "us_census_divisions__6e2dcd43-5f14-45b1-b850-f289673d89c7"
type = "geography"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "sector"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "subsector"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "end_use"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "weather_year"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "model_year"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "scenario"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "data_source"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "time"
version = "1.0.0"

