# dataset configuration file

dataset_id = "eia861"
dataset_type = "historical" # annual retail sales
model_name = "EIA 861"  # TODO: this isn't really needed either?
model_sector = 'eia861'  # TODO this may not be needed
path = "s3://nrel-dsgrid-scratch/dsgrid_v2.0.0/eia861/"
description = """
Historical annual retail sales of electricity (2001-2019), updated annually
"""

"""
TODO: 
   - where do we define what types of dimension mapping files to expect in the dataset's path?
   - where do we define the project dimension associations? this has to exist outside in the submittal
   - is it OK for the dataset to have the same class names as the project's? 

   - if the project requires a disaggregation (e.g., industrial), this needs to be in the files as a project_dimension_mapping.parquet of some form OR it needs to live in some other folder that gets associated to the project in some way.
"""

[[dimensions]] # same as project ATM
type = 'geography'
name = "County" # Utility, County, State
file = "dimensions/counties.csv"

[[dimensions]]
type = 'sector'
name = "Sector" # probably single field
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
class = "Sector"

[[dimensions]] 
type = 'subsector'
name = "EIA 861 Subsectors" # fields: Sales, Losses, Energy Without Charge
file = "dimensions/eai861_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "SubSector"

[[dimensions]]
type = 'end_use'
name = "End Use" # single field, no end use
file = "dimensions/enduses.csv"
module = "dsgrid.dimension.standard"
class = "EndUse"

[[dimensions]]
# def: the underlying model or root source of the dataset relative to the project, e.g. 'ComStock' within 'EFS Models'
type = 'model'
name = "Historical" # single field
file = "dimensions/models.csv"
module = "dsgrid.dimension.standard"
class = "Model"

[[dimensions]]
type = 'scenario'
name = "Standard Scenario" # single field
file = "dimensions/standard_scenarios.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"

[[dimensions]]
type = 'weather'
name = "Historical Weather Year" # historical data doesn't have weather, but can map to historcal weather files
file = "dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
class = "Weather"

[[dimensions]]
type = 'model_year'
name = "Historical Model Year" # see time # 2001-2019
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"

[[dimensions]]
type = 'time'
name = "Time"
start = "2001"
end = "2019"
frequency = "1 year"
includes_dst = false
# leap_day_adjustment = ""
period = "period_starting" 
str_format = "%Y"
timezone = None
value_representation = "mean"  

# [metadata]
# coverage_year = 2006-2020
# description = "Historical annual electricity retail sales, losses, and energy furnished without charge by utilities from EIA Form 861"
# geographic_scope = "US"
# notes = ""
# origin_creator = "xxx, NREL"
# origin_date = "03/18/2018"
# origin_project = "dsgrid v2"
