# translated from dsgrid efs using dan's script
# data located in: /projects/dsgrid/efs_datasets/loss_model

# In [16]: lookup.head()
# Out[16]: 
#   geography  id sector
# 0        AL   1    All
# 1        AZ   2    All
# 2        AR   3    All
# 3        CA   4    All
# 4        CO   5    All

# In [17]: data.head()
# Out[17]: 
#             timestamp         All  id
# 0 2012-01-01 06:00:00  469.949097   1
# 1 2012-01-01 07:00:00  459.798950   1
# 2 2012-01-01 08:00:00  446.293091   1
# 3 2012-01-01 09:00:00  437.876099   1
# 4 2012-01-01 10:00:00  436.073639   1

dataset_id = "dsgrid_efs_2012_losses"
dataset_type = "modeled"
data_source = "dsgrid_efs"
sector_description = "electricity"
description = "State-level estimates of distribution and transmission losses for historical year 2012 derived from FERC 714 (and similar) historical system-level timeseries profiles of 2012 load and 2012 losses reported on EIA Form 861. Details are in https://www.nrel.gov/docs/fy18osti/71492.pdf, starting on page 61."
origin_creator = "Elaine Hale"
origin_organization = "NREL"
origin_contributors = ["Elaine Hale"]
origin_project = "NREL Electrification Futures Study"
origin_date = "2018"
origin_version = "0.2.0"
source = "https://oedi-data-lake.s3.amazonaws.com/dsgrid-2018-efs/raw_complete/chp_dg.dsg"
data_classification = "low"
tags = ["losses", "efs", "2012", "dsgrid_v0.2.0"]
data_schema_type = "standard"
trivial_dimensions = ["weather_year", "model_year", "scenario", "data_source", "subsector"] 
# TODO: do we apply the same losses for every model year? for every scenario? @ehal says: We should apply the same loss rates for every model year and scenario. Basically we should have 2012 sales (EIA 861) + these losses = 2012 annual system load (FERC 714). For other years we would want to hold the ratios between sales and annual system load constant (compared to this data point).

# TODO: not sure if project association for data_source__model_year is correct here for dsgrid_efs_2012_losses. Do we expect only 2012 model year? Answer depends on TODO above.

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
type = "geography"
name = "states"
display_name = "States"
file = "../../../dimensions/supplemental/states.csv"
module = "dsgrid.dimension.standard"
class = "State"
description = "Lower 48 Contiguous US States"

[[dimensions]]
type = "sector"
name = "all-sectors"
display_name = "All Sectors"
file = "dimensions/sector.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = "All Sectors"

[[dimensions]]
type = "subsector"
name = "unspecified-subsectors"
display_name = "Subsector Unspecified"
file = "dimensions/subsectors.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = "Subsector Unspecified"

[[dimensions]] 
type = "metric"
name = "Unspecified Electricity"
display_name = "Unspecified Electricity"
file = "dimensions/metric.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse" 
description = "Unspecified Electricity"

[[dimensions]]
type = "data_source"
name = "dsgrid-efs"
display_name = "EFS"
file = "dimensions/data_source.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "dsgrid data for historical year 2012 created for the NREL Electrification Futures Study" 

# use the resstock scenario dimension
[[dimensions]]
type = "scenario"
name = "Conus-2022-reference"
display_name = "Reference"
file = "../../modeled/resstock/dimensions/scenario_conus_2022_reference.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = "CONUS (Continental U.S.) 2022 Reference"

[[dimensions]]
type = "model_year"
name = "Model-Year-2012"
display_name = "2012"
file = "dimensions/model_year.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = "2012 Model Year"

[[dimensions]] # shared with project
class = "WeatherYear"
description = "Weather year, 2012 only"
file = "../../../dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
display_name = "2012 Weather"
type = "weather_year"


# Note: this does not match the project time because of it being period-ending, not period-beginning
[[dimensions]]
name = "Time-2012-EST-hourly-periodEnding-noDST-noLeapDayAdjustment-total-UTChour1start"
display_name = "2012 Hourly EST"
type = "time"
module = "dsgrid.dimension.standard"
class = "Time"
description = "Time dimension, 2012 hourly EST, period-ending, no DST, no Leap Day Adjustment, total value"
time_type = "datetime"
measurement_type = "total"
str_format = "%Y-%m-%d %H:%M:%S"
frequency = "P0DT1H0M0.000000S"
leap_day_adjustment = "none"
time_interval_type = "period_ending"
timezone = "EasternStandard"
ranges = [{start = "2012-01-01 01:00:00", end = "2013-01-01 00:00:00"}]
