# --------------------------------------
# ResStock Dataset Configuration File
# --------------------------------------

dataset_id = "conus_2022_reference_resstock"
dataset_type = "sector_model"
data_source = "resstock"
description = """
Time-wrapped, simulated on 09/15/2021 using: 
ResStock version: https://github.com/NREL/resstock/releases/tag/eulp_final and
buildstock version: https://github.com/NREL/buildstockbatch/releases/tag/eulp_res_final 
(Post-processed using AWS SightGlass and notebooks from https://github.com/NREL/SightGlassDataProcessing/tree/agg_for_dsgrid)
"""

origin_creator = "Lixi Liu"
origin_organization = "NREL"
origin_contributors = ["Anthony Fortanini", "Lixi Liu", "Noah Sandoval"]
origin_project = "End Use Load Profiles"
origin_date = "2021-09-15"
origin_version = "0.1.0"
source = "s3://eulp/simulation_output/national_runs/resstock/eulp_res_final_2012_dsgrid/"
data_classification = "low"
tags = ["residential", "conus-2022", "reference", "dsgrid_v0.2.0", "standard_scenarios"]
data_schema_type = "standard"
trivial_dimensions = ["sector", "weather_year", "model_year", "scenario", "data_source"]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
type = "geography"
name = "conus_2022-resstock_US_county_FIP"
file = "dimensions/conus_2022-resstock_geography_county_fips.csv"
module = "dsgrid.dimension.standard"
class = "County"
description = """
CONUS 2022 - ResStock US county in original FIP code (N=3,108)
"""

[[dimensions]]
type = "sector"
name = "residential-sector"
file = "dimensions/sector_residential.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Residential sector only
"""

[[dimensions]]
type = "subsector"
name = "conus_2022-resstock_building_types"
file = "dimensions/conus_2022-resstock_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = """
CONUS 2022 - ResStock building types (N=5)
"""

[[dimensions]]
type = "metric"
name = "conus_2022-resstock_energy_enduses_kwh"
file = "dimensions/conus_2022-resstock_end_uses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
CONUS 2022 - ResStock end uses (N=48, 5 fuel types)
"""

[[dimensions]]
type = "data_source"
name = "ResStock-Data-Source"
file = "dimensions/data_source_resstock.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = """
ResStock only data source
"""

[[dimensions]]
type = "scenario"
name = "Conus-2022-reference"
file = "dimensions/scenario_conus_2022_reference.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
Scenario: CONUS (Continental U.S.) 2022 Reference
"""

[[dimensions]]
type = "model_year"
name = "Model-Year-2018"
file = "dimensions/model_year_2018.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model year, 2018 only
"""

[[dimensions]] # shared with project
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "../../../dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
type = "weather_year"

# [[dimensions]] # for real dataset
# name = "Time-2012-UTC-8784-hourly-periodEnding-total-Hour6Start-localRangesTZ"
# type = "time"
# module = "dsgrid.dimension.standard"
# class = "Time"
# description = "Time dimension, 2012 hourly UTC, period-ending, starts at Hour 6, 8784 timestamps, total value, local ranges_timezone"
# time_type = "datetime"
# measurement_type = "total"
# str_format = "%Y-%m-%d %H:%M:%S"
# frequency = "P0DT1H0M0.000000S"
# leap_day_adjustment = "none"
# time_interval_type = "period_ending"
# timezone = "UTC"
# ranges = [{start = "2012-01-01 01:00:00", end = "2013-01-01 00:00:00"}]
# ranges_timezone = "LOCAL"

[[dimensions]] # for time-wrapped dataset
class = "Time"
frequency = "P0DT1H0M0.000000S"
name = "Time-2012-EST-8784-hourly-periodEnding-noLeapDayAdjustment-total-Hour0Start"
ranges = [{start = "2012-01-01 00:00:00", end = "2012-12-31 23:00:00"}]
time_type = "datetime"
leap_day_adjustment = "none"
description = """
Time dimension, 2012 hourly EST, hour-ending, no Leap Day Adjustment, total value, starts at Hour 0
"""
time_interval_type = "period_ending"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "EasternStandard"
measurement_type = "total"
type = "time"
