id = "time-2012-utc-8787-hourly-periodending-total-hour6start__156f0b71-2535-4ae6-8397-f6721138f8c6"
name = "Time-2012-UTC-8787-hourly-periodEnding-total-Hour6Start"
type = "time"
module = "dsgrid.dimension.standard"
class = "Time"
description = "Time dimension, 2012 hourly UTC, period-ending, starts at Hour 6, 8787 timestamps, total value, local ranges_timezone"
time_type = "datetime"
measurement_type = "total"
str_format = "%Y-%m-%d %H:%M:%S"
frequency = "P0DT1H0M0.000000S"
leap_day_adjustment = "none"
time_interval_type = "period_ending"
timezone = "UTC"
ranges = [{start = "2012-01-01 06:00:00", end = "2013-01-01 08:00:00"}]
ranges_timezone = "LOCAL"