[[mappings]]
description = "ResStock CONUS 2022 counties to project counties"
file = "dimension_mappings/county_to_county.csv"
[mappings.from_dimension]
type = "geography"
dimension_id = "conus_2022-resstock_us_county_fip__bc1e70c9-7e75-48df-a052-90d25e0127de"
version = "1.0.0"
[mappings.to_dimension]
type = "geography"
dimension_id = "us_counties_2020_l48__3f48928c-e700-4e1d-b7fb-c35a52d076a0"
version = "1.0.0"

[[mappings]]
description = "Dummy model year mapping that repeats 2018 for all CONUS 2022 model years"
file = "dimension_mappings/model_year_to_model_year.csv"
[mappings.from_dimension]
type = "model_year"
dimension_id = "model-year-2018__055f9044-b09b-4372-830c-b6f08dd7ecc1"
version = "1.0.0"
[mappings.to_dimension]
type = "model_year"
dimension_id = "model_years_2010_to_2050_with_2_year_intervals__b26a5cd8-816c-44de-8648-a0a8b082b9a0"
version = "1.0.0"

[[mappings]]
description = "ResStock and ComStock scenario dataset-to-project dimension mapping for the CONUS 2022 project"
file = "dimension_mappings/scenario_to_scenario.csv"
[mappings.from_dimension]
type = "scenario"
dimension_id = "conus-2022-reference__a90f3ea4-b0ed-4c08-a15a-242fb802b156"
version = "1.0.0"
[mappings.to_dimension]
type = "scenario"
dimension_id = "dsgrid_conus_2022_scenarios__fcfa2979-d6c7-4811-9879-4ba09fe86777"
version = "1.0.0"

[[mappings]]
description = "ResStock CONUS 2022 energy end uses mapping to project"
file = "dimension_mappings/metric_to_metric.csv"
[mappings.from_dimension]
type = "metric"
dimension_id = "conus_2022-resstock_energy_enduses_kwh__e84ff30a-3db3-4369-8108-6b619d12761b"
version = "1.0.0"
[mappings.to_dimension]
type = "metric"
dimension_id = "conus-2022-detailed-end-uses-kwh__8b12e233-b2eb-41c3-b784-373274120d3b"
version = "1.0.0"