[[dimensions]]
description = "US counties, Census May 1st 2015 vintage, no territories"
file = "dimensions/counties.csv"
name = "US County - Census May 1st 2015 vintage"
type = "geography"

[[dimensions]]
class = "Sector"
description = "dsgrid Standard Scenarios 2021 Sectors;Residential Only"
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
name = "Standard Scenarios 2021 Sectors-Residential-Only"
type = "sector"

[[dimensions]]
class = "DataSource"
description = "dsgrid Standard Scenarios 2021 Data Sources;ResStock Only"
file = "dimensions/sources.csv"
module = "dsgrid.dimension.standard"
name = "Standard Scenarios 2021 DataSourcs -ResStock-Only"
type = "data_source"

[[dimensions]]
end = "2012-12-31 23:59:59"
frequency = "1 hour"
includes_dst = false
name = "Time-2012-localStandardTime-hourly-periodBeginning-noDST-noLeapDayAdjustment-mean"
start = "2012-01-01 01:00:00"
type = "time"
description = "Time dimension, 2012 hourly local standard time, hour-beginning, no DST, no Leap Day Adjustment, mean value"
period = "period_beginning"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "Local standard time"
value_representation = "mean"

