# # ------------------------------------------------------
# # Base Dimensions
# # ------------------------------------------------------
[[dimensions]]
description = """
US counties, Census 2020 vintage, no territories
"""
file = "dimensions/counties.csv"
name = "US Counties 2020"
type = "geography"
class = "County"

[[dimensions]]
class = "Sector"
description = """
dsgrid Standard Scenarios 2021 Sectors; Commercial, Residential, Transportation  Only
"""
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
name = "Standard Scenarios 2021 Sectors - Com-Res-Tra-Only"
type = "sector"

# TODO -- add the tempo dimensions for subsector for now
# [[dimensions]]
# type = "subsector"
# name = "Standard-Scenarios-2021-Detailed-Subsectors--Trans-Only"
# file = "dimensions/subsectors.csv"
# module = "dsgrid.dimension.standard"
# class = "Subsector"
# description = """
# dsgrid Standard Scenarios 2021 Subsectors; Transportation sector only
# """

# TODO -- add the tempo dimensions for enduses for now
# [[dimensions]]
# type = "end_use"
# name = "Standard-Scenarios-2021-Detailed-End-Uses--Trans-Only"
# file = "dimensions/enduses.csv"
# module = "dsgrid.dimension.standard"
# class = "EndUse"
# description = """
# dsgrid Standard Scenarios 2021 End Uses; Transportation only
# """

[[dimensions]]
class = "ModelYear"
description = """
Model year, 2010-2050, every other year
"""
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
name = "Model Years 2010 to 2050 with 2 year intervals"
type = "model_year"

[[dimensions]]
class = "Scenario"
description = """
Scenarios for the dsgrid CONUS 2022 project, which include a Reference scenario
and two light-duty vehicle electrification scenarios
"""
file = "dimensions/scenarios.csv"
module = "dsgrid.dimension.standard"
name = "dsgrid CONUS 2022 scenarios"
type = "scenario"

[[dimensions]]
class = "DataSource"
description = """
dsgrid Standard Scenarios 2021 Data Sources; ComStock, TEMPO, ResStock Only
"""
file = "dimensions/sources.csv"
module = "dsgrid.dimension.standard"
name = "Standard Scenarios 2021 DataSources - ComStock-ResStock-TEMPO-Only"
type = "data_source"

[[dimensions]]
class = "Time"
frequency = "P0DT1H0M0.000000S"
name = "Time-2012-UTC-houlry-periodBeginning-noDST-noLeapDayAdjustment-mean"
ranges = [{start = "2012-01-01 00:00:00", end = "2013-12-31 23:00:00"}]
type = "time"
time_type = "datetime"
leap_day_adjustment = "none"
description = """
Time dimension, 2012 hourly UTC, hour-beginning, no DST, no Leap Day Adjustment, mean value
"""
time_interval_type = "period_beginning"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "UTC"
measurement_type = "mean"
