# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions]]
description = """
US counties, Census 2010 vintage, no territories
"""
file = "dimensions/counties.csv"
name = "US-County-Census2010"
type = "geography"

[[dimensions]]
class = "Sector"
description = """
dsgrid Standard Scenarios 2021 Sectors; Transportation only
"""
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
name = "Standard-Scenarios-2021-Sectors--Trans-Only"
type = "sector"

# TODO
# [[dimensions]]
# type = "subsector"
# name = "Standard-Scenarios-2021-Detailed-Subsectors--Trans-Only"
# file = "dimensions/subsectors.csv"
# module = "dsgrid.dimension.standard"
# class = "SubSector"
# description = """
# dsgrid Standard Scenarios 2021 Subsectors; Transportation sector only
# """

# TODO
# [[dimensions]]
# type = "end_use"
# name = "Standard-Scenarios-2021-Detailed-End-Uses--Trans-Only"
# file = "dimensions/enduses.csv"
# module = "dsgrid.dimension.standard"
# class = "EndUse"
# description = """
# dsgrid Standard Scenarios 2021 End Uses; Transportation only
# """

[[dimensions]]
class = "Weather"
description = """
Weather year, 2012 only
"""
file = "dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012-Weather-Year"
type = "weather"

[[dimensions]]
class = "ModelYear"
description = """
Model year, 2010-2050, every other year
"""
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
name = "Model-Years-2010-to-2050-with-2yr-intervals"
type = "model_year"

[[dimensions]]
class = "Scenario"
description = """
base scenario only
"""
file = "dimensions/scenarios.csv"
module = "dsgrid.dimension.standard"
name = "Baseline-Scenario"
type = "scenario"

[[dimensions]]
class = "DataSource"
description = """
dsgrid Standard Scenarios 2021 Data Sources; TEMPO only
"""
file = "dimensions/sources.csv"
module = "dsgrid.dimension.standard"
name = "Standard-Scenarios-2021-DataSourcs--TEMPO-Only"
type = "data_source"

[[dimensions]]
end = "2012-12-31 23:59:59"
frequency = "1 hour"
includes_dst = false
name = "Time-2012-UTC-houlry-periodBeginning-noDST-noLeapDayAdjustment-mean"
start = "2012-01-01 01:00:00"
type = "time"
# leap_day_adjustment = ""
description = """
Time dimension, 2012 hourly UTC, hour-beginning, no DST, no Leap Day Adjustment, mean value
"""
period = "period_beginning"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "UTC"
value_representation = "mean"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions]]
description = """
US States
"""
file = "dimensions/supplemental/states.csv"
name = "US-State"
type = "geography"

[[dimensions]]
class = "CensusDivision"
description = """
US Census Divisions
"""
file = "dimensions/supplemental/census_divisions.csv"
name = "US-Census-Division"
type = "geography"

[[dimensions]]
class = "CensusRegion"
description = """
US Census Regions
"""
file = "dimensions/supplemental/census_regions.csv"
name = "US-Census-Region"
type = "geography"

