# TODO: This configuration is under active development. Currently it is set up for TEMPO data only but it will later be expanded to include all project configuration details.

project_id = "dsgrid-standard-scenarios-2021"
name = "dsgrid Standard Scenarios 2021"
description = """dsgrid Standard Scenarios project FY21"""

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
[input_datasets]
benchmark = [] # ignoring this for now
historical = [] # ignoring this for now

[[input_datasets.datasets]]
dataset_id = "comstock-standard-scenarios-2021"
version = "1.0.0"
dataset_type = "sector_model"
model_sector = "cld"

[[input_datasets.datasets]]
dataset_id = "resstock-standard-scenarios-2021"
version = "1.0.0"
dataset_type = "sector_model"
model_sector = "rld"

[[input_datasets.datasets]]
dataset_id = "tempo-standard-scenarios-2021"
version = "1.0.0"
dataset_type = "sector_model"
model_sector = "tld"

[dimensions]
# ------------------------------------------------------
# Project Dimensions
# ------------------------------------------------------
[[dimensions.project_dimensions]]
type = "geography"
dimension_id = "county__58f264b4-b83d-4554-96d0-1349852ff03d"
version = "1.0.0"

[[dimensions.project_dimensions]] # TODO
type = "sector"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]] # TODO
# required: subsector maps to sector
type = "subsector"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]] # TODO
# required: end use maps to [sector, subsector, model]
type = "end_use"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]] # TODO
# required: weather maps to [modelyear, scenario]
type = "weather"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]]
# required: model year maps to [scenario, weather, sector, model]
type = "model_year"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]]
# required: scenario maps to [model, weather]
type = "scenario"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]] # TODO
# model maps to [model_year, sector, subsector, enduse, scenario]
type = "model"
dimension_id = ""
version = ""

[[dimensions.project_dimensions]] # TODO
type = "time"
dimension_id = ""
version = ""

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
# TODO: Can we have supplemental time dimensions in project config?
# TODO: Do we really need to supply the supp dims here if they are all dsgrid standard?
# TODO: these all should REQUIRE mappings to project level dimension of the same type
[[dimensions.supplemental_dimensions]]
type = "geography"
dimension_id = ""
version = ""

[[dimensions.supplemental_dimensions]]
type = "geography"
dimension_id = ""
version = ""

[[dimensions.supplemental_dimensions]]
type = "geography"
dimension_id = ""
version = ""
