# TODO: This configuration is under active development. Currently it is set up for TEMPO data only but it will later be expanded to include all project configuration details.

description = """dsgrid Standard Scenarios project FY21"""
name = "dsgrid Standard Scenarios 2021"
project_id = "dsgrid_standard_scenarios_2021"

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
[input_datasets]
benchmark = [] # ignoring this for now
historical = [] # ignoring this for now

# [[input_datasets.datasets]]
# dataset_id = "comstock-standard-scenarios-2021"
# version = "1.0.0"
# dataset_type = "sector_model"
# model_sector = "cld"

# [[input_datasets.datasets]]
# dataset_id = "resstock-standard-scenarios-2021"
# version = "1.0.0"
# dataset_type = "sector_model"
# model_sector = "rld"

[[input_datasets.datasets]]
dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "tld"
version = "1.0.0"

[dimensions]
# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions.base_dimensions]] # TODO
dimension_id = "todo__XX"
type = "geography"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "sector"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
# required: subsector maps to sector
dimension_id = ""
type = "subsector"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
# required: end use maps to [sector, subsector, data_source]
dimension_id = ""
type = "end_use"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
# required: weather maps to [modelyear, scenario]
dimension_id = ""
type = "weather_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
# required: data_source year maps to [scenario, weather, sector, data_source]
dimension_id = ""
type = "model_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
# required: scenario maps to [data_source, weather]
dimension_id = ""
type = "scenario"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
# data_source maps to [model_year, sector, subsector, enduse, scenario]
dimension_id = ""
type = "data_source"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "time"
version = "1.0.0"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions.supplemental_dimensions]]
dimension_id = "us_states__2bae0844-b0d3-4bf0-9d15-d9d969dee774"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_regions__899a4862-883d-4f8f-820e-3921db84ea8e"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_divisions__6e2dcd43-5f14-45b1-b850-f289673d89c7"
type = "geography"
version = "1.0.0"
