# TODO: This configuration is under active development. Currently it is set up for TEMPO data only but it will later be expanded to include all project configuration details.

description = """dsgrid Standard Scenarios project FY21"""
name = "dsgrid Standard Scenarios 2021"
project_id = "dsgrid-standard-scenarios-2021"

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
[input_datasets]
benchmark = [] # ignoring this for now
historical = [] # ignoring this for now

# [[input_datasets.datasets]]
# dataset_id = "comstock-standard-scenarios-2021"
# version = "1.0.0"
# dataset_type = "sector_model"
# model_sector = "cld"

# [[input_datasets.datasets]]
# dataset_id = "resstock-standard-scenarios-2021"
# version = "1.0.0"
# dataset_type = "sector_model"
# model_sector = "rld"

[[input_datasets.datasets]]
dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "tld"
version = "1.0.0"

[dimensions]
# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "geography"
version = ""

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "sector"
version = ""

[[dimensions.base_dimensions]] # TODO
# required: subsector maps to sector
dimension_id = ""
type = "subsector"
version = ""

[[dimensions.base_dimensions]] # TODO
# required: end use maps to [sector, subsector, data_source]
dimension_id = ""
type = "end_use"
version = ""

[[dimensions.base_dimensions]] # TODO
# required: weather maps to [modelyear, scenario]
dimension_id = ""
type = "weather"
version = ""

[[dimensions.base_dimensions]]
# required: data_source year maps to [scenario, weather, sector, data_source]
dimension_id = ""
type = "model_year"
version = ""

[[dimensions.base_dimensions]]
# required: scenario maps to [data_source, weather]
dimension_id = ""
type = "scenario"
version = ""

[[dimensions.base_dimensions]] # TODO
# data_source maps to [model_year, sector, subsector, enduse, scenario]
dimension_id = ""
type = "data_source"
version = ""

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "time"
version = ""

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
# TODO: Can we have supplemental time dimensions in project config?
# TODO: Do we really need to supply the supp dims here if they are all dsgrid standard?
# TODO: these all should REQUIRE mappings to project level dimension of the same type
[[dimensions.supplemental_dimensions]]
dimension_id = ""
type = "geography"
version = ""

[[dimensions.supplemental_dimensions]]
dimension_id = ""
type = "geography"
version = ""

[[dimensions.supplemental_dimensions]]
dimension_id = ""
type = "geography"
version = ""
