# TODO: This configuration is under active development. Currently it is set up for TEMPO, ComStock, ResStock data only but it will later be expanded to include all project configuration details.

description = """dsgrid Standard Scenarios project FY21"""
name = "dsgrid Standard Scenarios 2021"
project_id = "dsgrid_standard_scenarios_2021"

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
[input_datasets]
benchmark = [] # ignoring this for now
historical = [] # ignoring this for now

[[input_datasets.datasets]]
dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "tempo"
version = "1.0.0"

[[input_datasets.datasets]]
dataset_id = "resstock-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "resstock"
version = "1.0.0"

[[input_datasets.datasets]]
dataset_id = "comstock-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "comstock"
version = "1.0.0"

[dimensions]
# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions.base_dimensions]]
dimension_id = "us_counties_2020__2dc5cf6d-600b-493d-81f6-20490565218d"
type = "geography"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "standard_scenarios_2021_sectors_-_com-res-tra-only__e1a83d86-2c7c-4cc8-88a3-27681c0b54a5"
type = "sector"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "subsector"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "end_use"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "2012_weather_year__78aeebf8-788c-4ffa-8df2-f581cf0e4d96"
type = "weather_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "model_years_2010_to_2050_with_2_year_intervals__b26a5cd8-816c-44de-8648-a0a8b082b9a0"
type = "model_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "reference_scenario__5894cef9-4838-4a25-b610-52557964ee1f"
type = "scenario"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "standard_scenarios_2021_datasources_-_comstock-resstock-tempo-only__bb99920b-1d45-4500-844e-ccf19a0be83b"
type = "data_source"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "time-2012-utc-houlry-periodbeginning-nodst-noleapdayadjustment-mean__60cb33cb-0951-4ca1-8987-17ffe0903318"
type = "time"
version = "1.0.0"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions.supplemental_dimensions]]
dimension_id = "us_states__2bae0844-b0d3-4bf0-9d15-d9d969dee774"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_regions__899a4862-883d-4f8f-820e-3921db84ea8e"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_divisions__6e2dcd43-5f14-45b1-b850-f289673d89c7"
type = "geography"
version = "1.0.0"

# ------------------------------------------------------
# Dimension Mappings
# ------------------------------------------------------
[[dimension_mappings.base_to_base]] # TODO
from_dimension_type = "sector"
mapping_id = ""
required_for_validation = true
to_dimension_type = "subsector"
version = "1.0.0"

# TODO: may need sector, subsector, end use mappings

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_census_regions__aa5b14a9-53c0-42a4-aa7d-eb7c9a279324"
to_dimension_type = "geography"
version = "1.0.0"

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_census_divisions__1126102b-6c0b-4779-99a8-e9e25af21e71"
to_dimension_type = "geography"
version = "1.0.0"

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_states__4740e88a-413f-4bf1-a993-25a6b0a4cba3"
to_dimension_type = "geography"
version = "1.0.0"
