# TODO: This configuration is under active development. Currently it is set up for TEMPO, ComStock, ResStock data only but it will later be expanded to include all project configuration details.

description = """Dataset created for the FY21 dsgrid Load Profile Tool for Grid Modeling project"""
name = "dsgrid CONUS 2022"
project_id = "dsgrid_conus_2022"
dimension_associations = ["dimension_associations/data_source__metric.csv", "dimension_associations/data_source__model_year.csv", "dimension_associations/data_source__sector.csv", "dimension_associations/data_source__subsector.csv", "dimension_associations/model_year__metric.csv", "dimension_associations/model_year__subsector.csv", "dimension_associations/scenario__data_source.csv", "dimension_associations/scenario__metric.csv", "dimension_associations/scenario__sector.csv", "dimension_associations/scenario__subsector.csv", "dimension_associations/sector__metric.csv", "dimension_associations/sector__model_year.csv", "dimension_associations/sector__subsector.csv", "dimension_associations/subsector__metric.csv"]

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
# [datasets]
# benchmark = [] # ignoring this for now
# historical = [] # ignoring this for now

[[datasets]]
dataset_id = "tempo_conus_2022"
dataset_type = "sector_model"
model_sector = "tempo"
version = "1.0.0"

[[datasets]]
dataset_id = "conus_2022_reference_resstock"
dataset_type = "sector_model"
model_sector = "resstock"
version = "1.0.0"

[[datasets]]
dataset_id = "conus_2022_reference_comstock"
dataset_type = "sector_model"
model_sector = "comstock"
version = "1.0.0"

[dimensions]
# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions.base_dimensions]]
description = """
US counties for L48, Census 2020 vintage, no territories
"""
file = "dimensions/counties.csv"
name = "US Counties 2020 L48"
type = "geography"
class = "County"

[[dimensions.base_dimensions]]
class = "Sector"
description = """
dsgrid Standard Scenarios 2021 Sectors; Commercial, Residential, Transportation  Only
"""
file = "dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
name = "Standard Scenarios 2021 Sectors - Com-Res-Tra-Only"
type = "sector"

[[dimensions.base_dimensions]]
type = "subsector"
name = "CONUS-2022-Detailed-Subsectors"
file = "dimensions/subsectors.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = "dsgrid CONUS 2022 Subsectors"

# [[dimensions.base_dimensions]] # TODO: this is what we ultimately want to be using for the project
# type = "metric"
# name = "CONUS-2022-Detailed-End-Uses"
# file = "dimensions/enduses.csv"
# module = "dsgrid.dimension.standard"
# class = "EnergyEndUse"
# description = "dsgrid CONUS 2022 End Uses"

[[dimensions.base_dimensions]] # TODO: this is for the dummy data deliverable
type = "metric"
name = "CONUS-2022-Detailed-End-Uses-kWh"
file = "dimensions/enduses_kwh.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "dsgrid CONUS 2022 End Uses w/ all units in kWh"

[[dimensions.base_dimensions]]
class = "ModelYear"
description = """
Model year, 2010-2050, every other year
"""
file = "dimensions/model_years.csv"
module = "dsgrid.dimension.standard"
name = "Model Years 2010 to 2050 with 2 year intervals"
type = "model_year"

[[dimensions.base_dimensions]]
class = "Scenario"
description = """
Scenarios for the dsgrid CONUS 2022 project, which include a Reference scenario
and two light-duty vehicle electrification scenarios
"""
file = "dimensions/scenarios.csv"
module = "dsgrid.dimension.standard"
name = "dsgrid CONUS 2022 scenarios"
type = "scenario"

[[dimensions.base_dimensions]]
class = "DataSource"
description = """
dsgrid Standard Scenarios 2021 Data Sources; ComStock, TEMPO, ResStock Only
"""
file = "dimensions/sources.csv"
module = "dsgrid.dimension.standard"
name = "Standard Scenarios 2021 DataSources - ComStock-ResStock-TEMPO-Only"
type = "data_source"

[[dimensions.base_dimensions]]
class = "Time"
frequency = "P0DT1H0M0.000000S"
name = "Time-2012-UTC-houlry-periodBeginning-noDST-noLeapDayAdjustment-total"
ranges = [{start = "2012-01-01 00:00:00", end = "2013-12-31 23:00:00"}]
type = "time"
time_type = "datetime"
leap_day_adjustment = "none"
description = """
Time dimension, 2012 hourly UTC, hour-beginning, no DST, no Leap Day Adjustment, total value
"""
time_interval_type = "period_beginning"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "UTC"
measurement_type = "total"

[[dimensions.base_dimensions]]
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
type = "weather_year"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions.supplemental_dimensions]]
class = "State"
description = """
US States
"""
file = "dimensions/supplemental/states.csv"
module = "dsgrid.dimension.standard"
name = "US States"
type = "geography"

[[dimensions.supplemental_dimensions]]
class = "CensusRegion"
description = """
US Census Regions
"""
file = "dimensions/supplemental/census_regions.csv"
name = "US Census Regions"
type = "geography"

[[dimensions.supplemental_dimensions]]
class = "CensusDivision"
description = """
US Census Divisions
"""
file = "dimensions/supplemental/census_divisions.csv"
name = "US Census Divisions"
type = "geography"

# ------------------------------------------------------
# Dimension Mappings
# ------------------------------------------------------
[[dimension_mappings.base_to_supplemental]]
description = "Maps Comstock US Counties 2020 L48 to CensusRegion"
file = "dimension_mappings/base_to_supplemental/lookup_county_to_censusregion.csv"
mapping_type = "many_to_one_aggregation"
[dimension_mappings.base_to_supplemental.from_dimension]
name = "US Counties 2020 L48"
type = "geography"
[dimension_mappings.base_to_supplemental.to_dimension]
name = "US Census Regions"
type = "geography"

[[dimension_mappings.base_to_supplemental]]
description = "Maps Comstock US Counties 2020 L48 to CensusDivision"
file = "dimension_mappings/base_to_supplemental/lookup_l48_county_to_censusdivision.csv"
mapping_type = "many_to_one_aggregation"
[dimension_mappings.base_to_supplemental.from_dimension]
type = "geography"
name = "US Counties 2020 L48"
[dimension_mappings.base_to_supplemental.to_dimension]
name = "US Census Divisions"
type = "geography"

[[dimension_mappings.base_to_supplemental]]
description = "Maps Comstock US Counties 2020 L48 to State"
file = "dimension_mappings/base_to_supplemental/lookup_county_to_state.csv"
mapping_type = "many_to_one_aggregation"
[dimension_mappings.base_to_supplemental.from_dimension]
name = "US Counties 2020 L48"
type = "geography"
[dimension_mappings.base_to_supplemental.to_dimension]
name = "US States"
type = "geography"
