# TODO: This configuration is under active development. Currently it is set up for TEMPO, ComStock, ResStock data only but it will later be expanded to include all project configuration details.

description = """dsgrid Standard Scenarios project FY21"""
name = "dsgrid Standard Scenarios 2021"
project_id = "dsgrid_standard_scenarios_2021"

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
[input_datasets]
benchmark = [] # ignoring this for now
historical = [] # ignoring this for now

[[input_datasets.datasets]]
dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "tempo"
version = "1.0.0"

[[input_datasets.datasets]]
dataset_id = "resstock-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "resstock"
version = "1.0.0"

[[input_datasets.datasets]]
dataset_id = "comstock-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "comstock"
version = "1.0.0"

[dimensions]
# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions.base_dimensions]]
dimension_id = "us_counties_2020__73ce4579-bdcc-4496-93d8-8bdb2b49a648"
type = "geography"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "standard_scenarios_2021_sectors_-_com-res-tra-0d-6d93e5e007e3"
type = "sector"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "subsector"
version = "1.0.0"

[[dimensions.base_dimensions]] # TODO
dimension_id = ""
type = "end_use"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "2012_weather_year__78aeebf8-788c-4ffa-8df2-f581cf0e4d96"
type = "weather_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "model_years_2010_to_2050_with_2_year_intervals__17fa2f67-ef7f-49c8-8388-f2b102367f76"
type = "model_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "reference_scenario__4b6defca-9212-4388-bc39-9cf4462b4527"
type = "scenario"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "standard_scenarios_2021_datasources_-_tempo-only__2f19c49f-7e2c-480f-abd2-cc3caef2f5dc"
type = "data_source"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "time-2012-utc-houlry-periodbeginning-nodst-noleapdayadjustment-mean__72c76c0f-0d5a-4c03-8cf2-d806c4130cd9"
type = "time"
version = "1.0.0"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions.supplemental_dimensions]]
dimension_id = "us_states__2bae0844-b0d3-4bf0-9d15-d9d969dee774"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_regions__899a4862-883d-4f8f-820e-3921db84ea8e"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_divisions__6e2dcd43-5f14-45b1-b850-f289673d89c7"
type = "geography"
version = "1.0.0"

# ------------------------------------------------------
# Dimension Mappings
# ------------------------------------------------------
[[dimension_mappings.base_to_base]] # TODO
from_dimension_type = "sector"
mapping_id = ""
required_for_validation = true
to_dimension_type = "subsector"
version = "1.0.0"

# TODO: may need sector, subsector, end use mappings

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_census_regions__aa5b14a9-53c0-42a4-aa7d-eb7c9a279324"
to_dimension_type = "geography"
version = "1.0.0"

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_census_divisions__1126102b-6c0b-4779-99a8-e9e25af21e71"
to_dimension_type = "geography"
version = "1.0.0"

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_states__4740e88a-413f-4bf1-a993-25a6b0a4cba3"
to_dimension_type = "geography"
version = "1.0.0"
