# TODO: This configuration is under active development. Currently it is set up for TEMPO, ComStock, ResStock data only but it will later be expanded to include all project configuration details.

description = """Dataset created for the FY21 dsgrid Load Profile Tool for Grid Modeling project"""
name = "dsgrid CONUS 2022"
project_id = "dsgrid_conus_2022"

# ------------------------------------------------------
# Input Datasets Dimensions
# ------------------------------------------------------
# [datasets]
# benchmark = [] # ignoring this for now
# historical = [] # ignoring this for now

[[datasets]]
dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "tempo"
version = "1.0.0"

[[datasets]]
dataset_id = "resstock-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "resstock"
version = "1.0.0"

[[datasets]]
dataset_id = "comstock-standard-scenarios-2021"
dataset_type = "sector_model"
model_sector = "comstock"
version = "1.0.0"

[dimensions]
# ------------------------------------------------------
# Base Dimensions
# ------------------------------------------------------
[[dimensions.base_dimensions]]
dimension_id = "us_counties_2020__2dc5cf6d-600b-493d-81f6-20490565218d"
type = "geography"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "standard_scenarios_2021_sectors_-_com-res-tra-only__e1a83d86-2c7c-4cc8-88a3-27681c0b54a5"
type = "sector"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "conus-2022-detailed-subsectors__d285bf0f-2aa0-4c4a-a7cb-81fc03239516"
type = "subsector"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "conus-2022-detailed-end-uses__49496f0b-eaa8-4f53-a325-d28c555178e1"
type = "metric"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "2012_weather_year__78aeebf8-788c-4ffa-8df2-f581cf0e4d96"
type = "weather_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "model_years_2010_to_2050_with_2_year_intervals__b26a5cd8-816c-44de-8648-a0a8b082b9a0"
type = "model_year"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "dsgrid_conus_2022_scenarios__fcfa2979-d6c7-4811-9879-4ba09fe86777"
type = "scenario"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "standard_scenarios_2021_datasources_-_comstock-resstock-tempo-only__bb99920b-1d45-4500-844e-ccf19a0be83b"
type = "data_source"
version = "1.0.0"

[[dimensions.base_dimensions]]
dimension_id = "time-2012-utc-houlry-periodbeginning-nodst-noleapdayadjustment-total__28b148e2-1dd4-461b-abe8-484addd3d553"
type = "time"
version = "1.0.0"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
[[dimensions.supplemental_dimensions]]
dimension_id = "us_states__caef7924-b019-4081-a08f-5da8f451ed23"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_regions__81589d89-7575-4ac2-8ee3-4a3f24e1595f"
type = "geography"
version = "1.0.0"

[[dimensions.supplemental_dimensions]]
dimension_id = "us_census_divisions__c98c6bb0-5c5a-4d36-971e-5082cb453cea"
type = "geography"
version = "1.0.0"

# ------------------------------------------------------
# Dimension Mappings
# ------------------------------------------------------
[[dimension_mappings.base_to_base]] # TODO
from_dimension_type = "sector"
mapping_id = ""
required_for_validation = true
to_dimension_type = "subsector"
version = "1.0.0"

# TODO: may need sector, subsector, end use mappings

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_census_regions__aa5b14a9-53c0-42a4-aa7d-eb7c9a279324"
to_dimension_type = "geography"
version = "1.0.0"

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_census_divisions__1126102b-6c0b-4779-99a8-e9e25af21e71"
to_dimension_type = "geography"
version = "1.0.0"

[[dimension_mappings.base_to_supplemental]]
from_dimension_type = "geography"
mapping_id = "us_counties_-_census_2010__us_states__4740e88a-413f-4bf1-a993-25a6b0a4cba3"
to_dimension_type = "geography"
version = "1.0.0"
