# geography
[[mappings]]
description = "EFS Losses State to County mapping using proportion of state population in 2012"
dimension_type = "geography"
file = "../../historical/eia_861_annual_energy_use_state_sector/dimension_mappings/state_to_county.csv"
mapping_type = "many_to_many_disaggregation"

# sector
[[mappings]]
description = "All Sectors to Unspecified Sector"
dimension_type = "sector"
file = "dimension_mappings/sector_to_sector.csv"
mapping_type = "one_to_one"

# metric
[[mappings]]
description = "All Electricity Metric to Electricity Unspecified Metric"
dimension_type = "metric"
file = "dimension_mappings/metric_to_metric.csv"
mapping_type = "one_to_one"

[[mappings]] # scenario
description = "EFS historical data to project scenarios"
dimension_type = "scenario"
file = "../../historical/eia_861_annual_energy_use_state_sector/dimension_mappings/scenario_to_scenario.csv"
mapping_type = "duplication"
