[[mappings]]
description = "Maps Baseline ResStock end uses to AEO 2021 condensed end uses"
file = "dimension_mappings/lookup_resstock_to_aeo2021_res_combined_enduses.csv"
[mappings.from_dimension]
dimension_id = "resstock_enduse_xxx" # <---
type = "metric"
version = "1.0.0"
[mappings.to_dimension]
dimension_id = "aeo2021_res_enduse_xxx" # <---
type = "metric"
version = "1.0.0"
