# ------------------------------------------------------
# AEO 2021 Reference Case Commercial Energy End Use Dimensions
# ------------------------------------------------------
# [[dimensions]] # already exists
# type = "geography"
# name = "US-Census-Divisions"
# file = "dimensions/us_census_divisions.csv"
# module = "dsgrid.dimension.standard"
# class = "CensusDivision"
# description = """
# US Census Divisions (N=9)
# """

# [[dimensions]] # already exists
# type = "sector"
# name = "Benchmark-commercial-sector"
# file = "dimensions/sector_commercial.csv"
# module = "dsgrid.dimension.standard"
# class = "Sector"
# description = """
# Benchmark Commercial Sector
# """

[[dimensions]]
type = "subsector"
name = "AEO2021-commercial-building-types-include-unspecified"
file = "dimensions/aeo2021_commercial_building_types_include_unspecified.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = """
AEO 2021 commercial building types (N=13), include Unspecified
"""

[[dimensions]]
type = "metric"
name = "AEO2021-commercial-energy-enduses"
file = "dimensions/aeo2021_commercial_energy_enduses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
AEO 2021 commercial energy end uses (N=22, from 11 end uses, 3 fuel types)
"""

# [[dimensions]] # see if we need to register new
# type = "scenario"
# name = "AEO-Reference-Scenario"
# file = "dimensions/aeo_reference_scenario.csv"
# module = "dsgrid.dimension.standard"
# class = "Scenario"
# description = """
# AEO Reference Scenario
# """

# [[dimensions]] # already registered
# type = "data_source"
# name = "AEO-2021-Data-Source"
# file = "dimensions/aeo2021_data_source.csv"
# module = "dsgrid.dimension.standard"
# class = "DataSource"
# description = """
# AEO 2021 Data Source
# """

[[dimensions]]
type = "weather_year"
name = "Weather_Years-trivial-2013_to_2050"
file = "dimensions/weather_years_trivial_2013_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "WeatherYear"
description = """
Weather years, 2013-2050, trivial, single record
"""

[[dimensions]]
type = "model_year"
name = "Model_Years-trivial-2013_to_2050"
file = "dimensions/model_years_trivial_2013_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model years, 2013-2050, trivial, single record
"""

[[dimensions]]
class = "Time"
description = """
Annual time 2013-2050
"""
frequency = "P365D"
name = "annual_time-2013_to_2050"
time_interval_type = "instantaneous"
ranges = [{start = "2013", end = "2050"}]
str_format = "%Y"
timezone = "none"
type = "time"
time_type = "datetime"
measurement_type = "total"


