data_source = "EIA_AEO_2019"
dataset_id = "eia_aeo_2019_electricity_and_loss_by_sector_and_census_division"
dataset_type = "benchmark"
description = """
electricity demand and loss (Quads) from 2017-2050 by sector and census division
"""
path = "s3://nrel-dsgrid-registry/data/aeo_2019_electricity_and_loss_by_sector_and_census_division/1.0.0"
[[dimensions]]
dimension_id = "us_census_divisions__6e2dcd43-5f14-45b1-b850-f289673d89c7"
type = "geography"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "sector"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "subsector"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "end_use"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "weather_year"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "model_year"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "scenario"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "data_source"
version = "1.0.0"

[[dimensions]]
dimension_id = ""
type = "time"
version = "1.0.0"

