# ------------------------------------------------------
# AEO 2021 Reference Case Residential Household Unit Count Dimensions
# ------------------------------------------------------
[[dimensions]]
type = "geography"
name = "US-Census-Divisions"
file = "dimensions/us_census_divisions.csv"
module = "dsgrid.dimension.standard"
class = "CensusDivision"
description = """
US Census Divisions (N=9)
"""

[[dimensions]]
type = "sector"
name = "Benchmark-residential-sector"
file = "dimensions/sector_residential.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Benchmark Residential Sector
"""

[[dimensions]]
type = "subsector"
name = "AEO2021-residential-building-types"
file = "dimensions/aeo2021_residential_building_types.csv"
module = "dsgrid.dimension.standard"
class = "SubSector"
description = """
AEO 2021 residential building types (N=3)
"""

[[dimensions]]
type = "metric"
name = "AEO2021-residential-household-unit"
file = "dimensions/aeo2021_residential_household_unit.csv"
module = "dsgrid.dimension.standard"
class = "Stock"
description = """
AEO 2021 residential household unit count
"""

[[dimensions]]
type = "scenario"
name = "AEO-Reference-Scenario"
file = "dimensions/aeo_reference_scenario.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
AEO Reference Scenario
"""

[[dimensions]]
type = "data_source"
name = "AEO-2021-Reference-Case-Data-Source"
file = "dimensions/aeo2021_ref_data_source.csv"
module = "dsgrid.dimension.standard"
class = "Model"
description = """
AEO 2021 Reference Case Data Source
"""

[[dimensions]]
type = "weather"
name = "Weather-Years-2015-to-2050"
file = "dimensions/weather_years_2015_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "Weather"
description = """
Weather years, 2015-2050
"""

[[dimensions]]
type = "model_year"
name = "Model-Years-2015-to-2050"
file = "dimensions/model_years_2015_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model years, 2013-2050
"""

[[dimensions]]
class = "AnnualTime"
description = """Annual time, 2015-2050"""
module = "dsgrid.dimension.standard"
name = "Annual-Time-2015-to-2050"
measurement_type = "total"
include_leap_day = true
type = "time"
time_type = "annual"

