# ------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------
# [[dimensions]]
# name = "United States Excluding Territories"
# type = "geography"

# [[dimensions]]
# name = "Residential"
# type = "sector"

# [[dimensions]]
# name = "All Subsectors Combined"
# type = "subsector"

[[dimensions]]
class = "EndUse"
description = """EIA AEO electricity demand and loss: residential end uses (valid for AEO 2021 and up)
"""
file = "dimensions/eia_aeo_residential_enduses_valid_for_post_2020.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO Residential End Uses-Valid Post-2020"
type = "end_use"

# [[dimensions]]
# name = "EIA AEO Weather Years 2020-2050"
# type = "weather_year"

# [[dimensions]]
# name = "EIA AEO Model Years 2020-2050"
# type = "model_year"

# [[dimensions]]
# name = "EIA AEO Reference"
# type = "scenario"

# [[dimensions]]
# name = "EIA AEO 2021"
# type = "data_source"

# [[dimensions]]
# name = "Time-2020-2050-annual"
# type = "time"