# ------------------------------------------------------
# AEO 2021 Reference Case Transportation Miles Traveled Dimensions
# ------------------------------------------------------

[[dimensions]]
type = "sector"
name = "Benchmark-transportation-sector"
file = "dimensions/sector_transportation.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Benchmark Transportation Sector
"""

[[dimensions]]
type = "metric"
name = "AEO2021-transportation-miles-traveled-by-mode"
file = "dimensions/aeo2021_trans_miles_traveled_metrics.csv"
module = "dsgrid.dimension.standard"
class = "Stock"
description = """
AEO 2021 transportation miles traveled by mode of transportation (N=8)
"""

[[dimensions]]
type = "weather"
name = "Weather-Years-2020-to-2050"
file = "dimensions/weather_years_2020_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "Weather"
description = """
Weather years, 2020-2050
"""

[[dimensions]]
type = "model_year"
name = "Model-Years-2020-to-2050"
file = "dimensions/model_years_2020_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model years, 2020-2050
"""

[[dimensions]]
type = "scenario"
name = "AEO-Reference-Scenario"
file = "dimensions/aeo_reference_scenario.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
AEO Reference Scenario
"""

[[dimensions]]
type = "data_source"
name = "AEO-2021-Reference-Case-Data-Source"
file = "dimensions/aeo2021_ref_data_source.csv"
module = "dsgrid.dimension.standard"
class = "Model"
description = """
AEO 2021 Reference Case Data Source
"""

[[dimensions]]
class = "AnnualTime"
description = """Annual time, 2020-2050"""
module = "dsgrid.dimension.standard"
name = "Annual-Time-2020-to-2050"
measurement_type = "total"
include_leap_day = true
type = "time"
time_type = "annual"


### trvial dimensions below ###
# [[dimensions]]
# type = "geography"
# name = ""
# file = ""
# module = "dsgrid.dimension.standard"
# class = "CensusDivision"
# description = """
# None or trivial
# """

# [[dimensions]]
# type = "subsector"
# name = ""
# file = ""
# module = "dsgrid.dimension.standard"
# class = "SubSector"
# description = """
# None or trivial
# """
