# ------------------------------------------------------
# AEO 2021 Reference Case Commercial Sqft Growth Factors Dimensions
# ------------------------------------------------------
[[dimensions]]
type = "geography"
name = "US-Census-Divisions"
file = "dimensions/us_census_divisions.csv"
module = "dsgrid.dimension.standard"
class = "CensusDivision"
description = """
US Census Divisions (N=9)
"""

[[dimensions]]
type = "sector"
name = "Benchmark-commercial-sector"
file = "dimensions/sector_commercial.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Benchmark Commercial Sector
"""

[[dimensions]]
type = "subsector"
name = "AEO2021-commercial-building-types"
file = "dimensions/aeo2021_commercial_building_types.csv"
module = "dsgrid.dimension.standard"
class = "SubSector"
description = """
AEO 2021 commercial building types
"""

[[dimensions]]
type = "metric"
name = "AEO2021-commercial-stock-metrics"
file = "dimensions/aeo2021_commercial_stock_metrics.csv"
module = "dsgrid.dimension.standard"
class = "Stock"
description = """
AEO 2021 commercial stock metrics (sqft only)
"""

[[dimensions]]
type = "scenario"
name = "AEO-Reference-Scenario"
file = "dimensions/aeo_reference_scenario.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
AEO Reference Scenario
"""

[[dimensions]]
type = "data_source"
name = "AEO-2021-Reference-Case-Data-Source"
file = "dimensions/aeo2021_ref_data_source.csv"
module = "dsgrid.dimension.standard"
class = "Model"
description = """
AEO 2021 Reference Case Data Source
"""


### Trivial Dimensions Below ###

[[dimensions]]
type = "weather"
name = ""
file = ""
module = "dsgrid.dimension.standard"
class = "Weather"
description = """
None or trivial
"""

[[dimensions]]
type = "model_year"
name = ""
file = ""
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
None or trivial
"""

[[dimensions]]
class = "Time"
description = """None or trivial"""
module = "dsgrid.dimension.standard"
name = ""
measurement_type = ""
type = "time"
time_type = ""
