dataset_id = "eia_861_annual_energy_use_state_sector"
data_source = "EIA 861"
dataset_type = "historical"
data_schema_type = "one_table"
description = "EIA 861 Utility Customer Sales by State by Sector by Year for 2012-2020"
origin_creator = "Meghan Mooney"
origin_organization = "EIA"
origin_contributors = [ "Lixi Liu", "Meghan Mooney", "Elaine Hale",]
origin_project = "dsgrid Standard Scenarios" # TODO: what is this?
origin_date = "2022-08-17"
origin_version = "0.1.0"
source = "Data extracted from EIA 861 utility customer sales"
data_classification = "low"
tags = ["historical", "eia861", "sales"]
trivial_dimensions = [ "subsector", "scenario", "data_source", "weather_year", "model_year"]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]] # already exists
# TODO: pull the right states dimension
type = "geography"
name = "US_Census_Divisions"
display_name = "Census Division"
file = "dimensions/us_census_divisions.csv"
module = "dsgrid.dimension.standard"
class = "CensusDivision"
description = ""

[[dimensions]] # already exists
# TODO: pull the right sector dimension
type = "sector"
name = ""
display_name = ""
file = ""
module = "dsgrid.dimension.standard"
class = "Sector"
description = ""

# TODO - how do we apply all subsectors?
[[dimensions]]
type = "subsector"
name = ""
display_name = ""
file = ""
module = "dsgrid.dimension.standard"
class = "Subsector"
description = ""

[[dimensions]]
type = "metric"
name = "EIA861_customer_sales"
display_name = "Customer Sales"
file = "dimensions/eia861_sales_metric.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "Utility Customer Electricity Sales (MWh)"


# TODO: do we have a scenario for historical data?
[[dimensions]]
type = "scenario"
name = ""
display_name = ""
file = ""
module = "dsgrid.dimension.standard"
class = "Scenario"
description = ""

[[dimensions]] # already registered
type = "data_source"
name = "Data-Source-EIA861"
display_name = "EIA 861"
file = "dimensions/aeo2021_data_source.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "EIA 861"
# should I add more descriptions like Sales_Utl_Cust_XXXX and Disposition table used?

# @ehale: is this right? how are we handling weather year for historic datasets since it will conflict with the project's?
[[dimensions]]
type = "weather_year"
name = "Weather_Years-trivial-2012_to_2020"
display_name = "None"
file = "dimensions/weather_years_trivial_2012_to_2020.csv"
module = "dsgrid.dimension.standard"
class = "WeatherYear"
description = "Weather years, 2012-2020"

[[dimensions]]
type = "model_year"
name = "Model_Years-2012_to_2020"
display_name = "None"
file = "dimensions/model_years_2012_to_2020.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = "Model years, 2012-2020"


# Should this be converted to no-op time?
[[dimensions]]
type = "time"
class = "AnnualTime"
time_type = "annual"
module = "dsgrid.dimension.standard"
description = "Annual time 2012-2020"
name = "annual_time-2012_to_2020"
display_name = "Annual"
ranges = [{start = "2012", end = "2020"}]
str_format = "%Y"
include_leap_day = true
measurement_type = "total"