dataset_id = "eia_861_annual_energy_use_state_sector"
data_source = "EIA 861"
dataset_type = "historical"
data_schema_type = "one_table"
description = "EIA 861 Utility Customer Sales (MWh) by State by Sector by Year for 2010-2020"
origin_creator = "Meghan Mooney"
origin_organization = "EIA"
origin_contributors = [ "Lixi Liu", "Meghan Mooney", "Elaine Hale",]
origin_project = "dsgrid Standard Scenarios 2021" # TODO: what is this?
origin_date = "2022-08-17"
origin_version = "0.1.0"
source = "Data extracted from EIA 861 utility customer sales"
data_classification = "low"
tags = ["historical", "eia861", "sales"]
trivial_dimensions = [ "subsector", "scenario", "data_source", "weather_year", "model_year"]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]] # already exists
type = "geography"
name = "US States"
display_name = "State"
file = "../../../dimensions/supplemental/states.csv"
module = "dsgrid.dimension.standard"
class = "CensusDivision"
description = ""


[[dimensions]] # already exists
type = "sector"
name = "Sectors - Com-Res-Tra-Only"
display_name = "Sector"
file = "../../../dimensions/sectors.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = ""

# TODO - how do we apply all subsectors?
[[dimensions]]
type = "subsector"
name = "All Subsectors"
display_name = "All Subsectors"
file = "dimensions/subsectors_all.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = ""

[[dimensions]]
type = "metric"
name = "EIA861_customer_sales"
display_name = "Customer Sales"
file = "dimensions/eia861_sales_metric.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = "Utility Customer Electricity Sales (MWh)"

[[dimensions]] # use the same file as resstock
type = "scenario"
name = "Conus-2022-reference"
display_name = "Reference"
file = "../../sector_models/resstock/dimensions/scenario_conus_2022_reference.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = "Scenario CONUS (Continental U.S.) 2022 Reference"

[[dimensions]]
type = "data_source"
name = "Data-Source-EIA861"
display_name = "EIA 861"
file = "dimensions/data_source_eia861.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = "EIA 861"

[[dimensions]]
type = "weather_year"
name = "Weather_Years-2010_to_2020"
display_name = "None"
file = "dimensions/weather_years_2010_to_2020.csv"
module = "dsgrid.dimension.standard"
class = "WeatherYear"
description = "Weather years, 2010-2020"

[[dimensions]]
type = "model_year"
name = "Model_Years-2010_to_2020"
display_name = "None"
file = "dimensions/model_years_2010_to_2020.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = "Model years, 2010-2020"


# Should this be converted to no-op time?
[[dimensions]]
type = "time"
class = "AnnualTime"
time_type = "annual"
module = "dsgrid.dimension.standard"
description = "Annual time 2010-2020"
name = "annual_time-2010_to_2020"
display_name = "Annual"
ranges = [{start = "2010", end = "2020"}]
str_format = "%Y"
include_leap_day = true
measurement_type = "total"