[[mappings]] # geography
description = "EIA 861 State to County mapping using proportion of state population in 2012"
dimension_type = "geography"
file = "dimension_mappings/state_to_county.csv"
mapping_type = "many_to_many_disaggregation"

[[mappings]] # weather_year
description = "historic 2010-2020 weather year mapping to project weather year of 2012"
dimension_type = "weather_year"
file = "dimension_mappings/weather_year_to_weather_year.csv"
mapping_type = "many_to_one_reassignment"

[[mappings]] # metric
description = "EIA 861 electricity sales to project's unspecified end use metric"
dimension_type = "metric"
file = "dimension_mappings/metric_to_metric.csv"
mapping_type = "one_to_one"

[[mappings]] # scenario
description = "EIA 861 historical data to project scenarios"
dimension_type = "scenario"
file = "dimension_mappings/scenario_to_scenario.csv"
mapping_type = "duplication"

