# ------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------
[[dimensions]]
class = "Geography"
description = """US only"""
file = "dimensions/us_only.csv"
module = "dsgrid.dimension.standard"
name = "US only"
type = "geography"

[[dimensions]]
class = "Sector"
description = """EIA AEO electricity demand and loss: industrial sector only
"""
file = "dimensions/sector_industrial_only.csv"
module = "dsgrid.dimension.standard"
name = "industrial only"
type = "sector"

[[dimensions]]
class = "SubSector"
description = """EIA AEO electricity demand and loss: no sub-sector
"""
file = "dimensions/eia_aeo_electricity_demand_subsectors.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO electricity demand subsectors"
type = "subsector"

[[dimensions]]
# required: end use maps to [sector, subsector, model]
class = "EndUse"
description = """EIA AEO electricity demand and loss: industrial end uses
"""
file = "dimensions/eia_aeo_electricity_demand_industrial_enduses.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO electricity demandend uses"
type = "end_use"

[[dimensions]]
class = "WeatherYear"
description = """
EIA AEO weather years: 2017 - 2050
"""
file = "dimensions/weather_years_2017_to_2050.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO Weather Years"
type = "weather_year"

[[dimensions]]
class = "ModelYear"
description = """
EIA AEO model years: 2017 - 2050
"""
file = "dimensions/model_years_2017_to_2050.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO Model Years"
type = "model_year"

[[dimensions]]
class = "Scenario"
description = """
Baseline scenario
"""
file = "dimensions/scenarios.csv"
module = "dsgrid.dimension.standard"
name = "Baseline Scenario"
type = "scenario"

[[dimensions]]
class = "DataSource"
description = """
EIA AEO 2019 electricity demand projection
"""
file = "dimensions/eia_aeo_2019_data_sources.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO electricity demand projection"
type = "data_source"

[[dimensions]]
class = "Time"
description = """
Time dimension, 2017 - 2050, annual
"""
end = "2050"
frequency = "1 year"
includes_dst = false
name = "Time-2017-2050-annual"
period = "period_beginning"
start = "2017"
str_format = "%Y"
timezone = "UTC" # what should it be for year
type = "time"
value_representation = "total"

# ------------------------------------------------------
# Supplemental Dimensions
# ------------------------------------------------------
# need to create
# [[dimensions]]
# class = "State"
# description = """
# US States
# """
# file = "dimensions/supplemental/states.csv"
# module = "dsgrid.dimension.standard"
# name = "US States"
# type = "geography"

# [[dimensions]]
# class = "CensusDivision"
# description = """
# US Census Divisions
# """
# file = "dimensions/supplemental/census_divisions.csv"
# name = "US Census Divisions"
# type = "geography"

# [[dimensions]]
# class = "CensusRegion"
# description = """
# US Census Regions
# """
# file = "dimensions/supplemental/census_regions.csv"
# name = "US Census Regions"
# type = "geography"
