# ------------------------------------------------------
# AEO 2021 Reference Case Industrial Energy End Uses Dimensions
# ------------------------------------------------------
[[dimensions]]
type = "geography"
name = "US-Census-Regions"
file = "dimensions/us_census_regions.csv"
module = "dsgrid.dimension.standard"
class = "CensusRegion"
description = """
US Census Regions (N=4)
"""

[[dimensions]]
type = "sector"
name = "Benchmark-industrial-sector"
file = "dimensions/sector_industrial.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Benchmark Industrial Sector
"""

[[dimensions]]
type = "subsector"
name = "AEO2021-industrial-subsectors"
file = "dimensions/aeo2021_industrial_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "SubSector"
description = """
AEO 2021 industrial subsectors (N=22), including refining
"""

[[dimensions]]
type = "metric"
name = "AEO2021-industrial-energy-enduses"
file = "dimensions/aeo2021_industrial_energy_enduses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
AEO 2021 industrial energy end uses, total by fuel type (N=27)
"""

[[dimensions]]
type = "weather"
name = "AEO2021-Weather-Years-2014-to-2050"
file = "dimensions/weather_years_2014_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "Weather"
description = """
Weather years, 2014-2050
"""

[[dimensions]]
type = "model_year"
name = "2012-Model-Year"
file = "dimensions/model_years_2014_to_2050.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model years, 2014-2050
"""

[[dimensions]]
type = "scenario"
name = "AEO-Reference-Scenario"
file = "dimensions/aeo_reference_scenario.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
AEO Reference Scenario
"""

[[dimensions]]
type = "data_source"
name = "AEO-2021-Reference-Case-Data-Source"
file = "dimensions/aeo2021_ref_data_source.csv"
module = "dsgrid.dimension.standard"
class = "Model"
description = """
AEO 2021 Reference Case Data Source
"""

[[dimensions]]
class = "AnnualTime"
description = """Annual time, 2014-2050"""
module = "dsgrid.dimension.standard"
name = "Annual-Time-2014-to-2050"
measurement_type = "total"
include_leap_day = true
type = "time"
time_type = "annual"
