# ------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------
# [[dimensions]]
# name = "United States"
# type = "geography"

[[dimensions]]
class = "Sector"
description = """EIA AEO electricity demand and loss: residential sector only
"""
file = "dimensions/sector_residential.csv"
module = "dsgrid.dimension.standard"
name = "Residential"
type = "sector"

# [[dimensions]]
# name = "All Building Types Combined"
# type = "subsector"

[[dimensions]]
# required: end use maps to [sector, subsector, model]
class = "EndUse"
description = """EIA AEO electricity demand and loss: residential end uses (valid for AEO 2020 and before)
"""
file = "dimensions/eia_aeo_residential_enduses_valid_for_pre_2021.csv"
module = "dsgrid.dimension.standard"
name = "EIA AEO Residential End Uses-Valid Pre-2021"
type = "end_use"

# [[dimensions]]
# name = "EIA AEO Weather Years 2016-2050"
# type = "weather_year"

# [[dimensions]]
# name = "EIA AEO Model Years 2016-2050"
# type = "model_year"

# [[dimensions]]
# name = "EIA AEO Reference"
# type = "scenario"

# [[dimensions]]
# name = "EIA AEO 2018"
# type = "data_source"

# [[dimensions]]
# name = "time-2016-2050-annual"
# type = "time"
