# --------------------------------------
# TEMPO Dataset Configuration File
# --------------------------------------

dataset_id = "tempo_conus_2022"
dataset_type = "sector_model"
data_source = "tempo"

path = "/projects/dsgrid/tempo/data_02082022"
description = """
CONUS 2022 TEMPO county-level results for PEV charging."""

origin_creator = "Arthur Yip"
origin_organization = "NREL"
origin_contributors = ["Arthur Yip", "Brian Bush", "Christopher Hoehne", "Paige Jadun", "Catherine Ledna", "Matteo Muratori"]
origin_project = "dsgrid CONUS 2022"
origin_date = "Dec 21 2021"
origin_version = "dsgrid"
source = "https://github.nrel.gov/mmurator/TMM/commit/54f715e0fe015a578dd0594c7031c046cfe27907"
data_classification = "low"
tags = [ "transportation", "conus-2022", "reference", "tempo"]
data_schema_type = "standard"
trivial_dimensions = [ "sector", "weather_year", "scenario", "data_source"] # TODO: for non-dummy version, we will remove scenario from trivial dimensions

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
class = "County"
type = "geography"
name = "ACS County 2018"
file = "dimensions/counties.csv"
description = """
American Community Survey US counties, 2018."""

[[dimensions]]
class = "Subsector"
type = "subsector"
name = "TEMPO Bin"
file = "dimensions/bin.csv"
description = """
TEMPO demographic/geographic/vehicle bins.

This is a cross-join of the following supplemental dimensions:
* Composition (Single Driver, Some Drivers Smaller, Some Drivers Larger)
* Income (Low Income, Middle Income, High Income)
* Urbanity (Rural, Small Town, Suburban, Second City, Urban)
* Vehicle Size Class (Compact, Midsize, SUV, Pickup)
* Tech (PHEV25/PHEV50/BEV100/BEV300) """

[[dimensions]]
class = "EnergyEndUse"
type = "metric"
name = "TEMPO LDV PEV Usage"
file = "dimensions/end_use.csv"
description = """
Type of charging (L1 and L2, DCFC) used by TEMPO PEVs."""

[[dimensions]]
class = "Time"
type = "time"
name = "Time of Week by Month"
ranges = [{start = 1, end = 12}]
time_interval_type = "period_ending"
time_type = "representative_period"
measurement_type = "total"
format = "one_week_per_month_by_hour"
description = """
TEMPO Time - Month (representing seasons), day of week, and hour of day."""

[[dimensions]]
class = "DataSource"
type = "data_source"
name = "TEMPO Model"
file = "dimensions/data_source.csv"
description = """
TEMPO model"""

[[dimensions]]
class = "ModelYear"
type = "model_year"
name = "TEMPO Model Year"
file = "dimensions/year.csv"
description = """
TEMPO modeling years for CONUS 2022 project, 2018-2050"""

[[dimensions]]
class = "Sector"
type = "sector"
name = "Transportation Sector"
file = "dimensions/sector.csv"
description = """Transportation Sector"""

# TODO: remove this scenario dimension when we are ready to scrap the dummy dataset
[[dimensions]]
class = "Scenario"
type = "scenario"
name = "LDV Sales All-EV by 2035"
file = "dimensions/scenario.csv"
description = """
LDV Sales All-EV by 2035"""

# TODO: uncomment and add registered scenario dimension for final-dataset
# [[dimensions]]
# type = "scenario"
# dimension_id = "dsgrid_conus_2022_scenarios__fcfa2979-d6c7-4811-9879-4ba09fe86777"
# version = "1.0.0"

[[dimensions]] # shared with project
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "../../../dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
type = "weather_year"
