# --------------------------------------
# TEMPO Dataset Configuration File
# --------------------------------------

# TODO: TEMPO contributors to fill out this config file

dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_name = "TEMPO"
path = "s3://"
description = """"""

[[dimensions]]
type = "geography"
dimension_id = ""
version = ""

[[dimensions]]
type = "sector"
dimension_id = ""
version = ""

[[dimensions]]
type = "subsector"
dimension_id = ""
version = "1.0.0"

[[dimensions]]
type = "end_use"
dimension_id = ""
version = ""

[[dimensions]]
type = "data_source"
dimension_id = ""
version = ""

[[dimensions]]
type = "scenario"
dimension_id = ""
version = ""

[[dimensions]]
type = "weather"
dimension_id = ""
version = ""

[[dimensions]]
type = "model_year"
dimension_id = "2012_model_year__cd4ea2cf-aa79-4260-b143-3b68b59d6667"
version = "1.0.0"

[[dimensions]]
type = "time"
dimension_id = ""
version = ""

# [metadata]
# coverage_year = 2012
# description = ""
# geographic_resolution = ""
# geographic_scope = ""
# notes = ""
# origin_creator = ""
# origin_contributors = [""] # list of other contributors first and last name
# origin_organization = "NREL"
# origin_date =  # e.g., "06/17/2018"
# origin_project = ""
# tags = [""]
# data_class = "low"