# --------------------------------------
# TEMPO Dataset Configuration File
# --------------------------------------

# TODO: TEMPO contributors to fill out this config file
# TODO: Direct questions to brian.bush@nrel.gov

dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_name = "TEMPO"
path = "s3://" # FIXME
description = """
TEMPO county-level results for BEV charging.
"""

[[dimensions]]
type = "geography"
dimension_id = "" # FIXME: How are UUIDs generated? Where is the registry?
version = "" # FIXME: Are we using semantic versioning?

[[dimensions]]
type = "sector" # FIXME: TEMPO is just the transportation sector.
dimension_id = ""
version = ""

[[dimensions]]
type = "subsector" # FIXME: Would this be something like "LDV BEV"?
dimension_id = ""
version = "1.0.0"

[[dimensions]]
type = "end_use"
dimension_id = ""
version = ""

[[dimensions]]
type = "data_source" # FIXME: Would this just be "TEMPO"?
dimension_id = ""
version = ""

[[dimensions]]
type = "scenario" # FIXME: Discuss.
dimension_id = ""
version = ""

[[dimensions]]
type = "weather" # FIXME: Coordinate w/ Arthur on this.
dimension_id = ""
version = ""

[[dimensions]]
type = "model_year" # FIXME: Historically, we sum over this in TEMPO output.
dimension_id = ""
version = ""

[[dimensions]]
type = "time" # FIXME: TEMPO has two time dimensions: year and hour of week.
dimension_id = ""
version = ""

[[metadata]]
coverage_year = 2012 # FIXME: Discuss.
description = "TEMPO BEV results."
geographic_resolution = "County"
geographic_scope = "United States"
notes = "provisional sample data"
origin_creator = "Brian Bush"
origin_contributors = ["Brian Bush", "Arthur Yip"]
origin_organization = "NREL"
origin_date =  "2021-04-
origin_project = "TEMPO"
tags = ["TEMPO"]
data_class = "low"
source = "https://github.nrel.gov/mmurator/TMM/blob/0d89b8f61c624770643a35de1998efe6def5e59c/TEMPO.jl/src/BEV/BEV.jl"
