# --------------------------------------
# TEMPO Dataset Configuration File
# --------------------------------------

# TODO: TEMPO contributors to fill out this config file
# TODO: Direct questions to brian.bush@nrel.gov

dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_name = "TEMPO"
path = "s3://" # TODO: The registration process will provide this.
description = """
TEMPO county-level results for BEV charging.
"""

[[dimensions]]
type = "geography"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "sector" # FIXME: TEMPO is just the transportation sector.
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "subsector"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "end_use"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "time"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "data_source"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "model_year"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "scenario"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[dimensions]]
type = "weather_year"
dimension_id = "" # TODO: The registration process will provide this.
version = "0.1.0"

[[metadata]]
coverage_year = "2018-2050"
description = "TEMPO BEV results."
geographic_resolution = "County"
geographic_scope = "United States"
notes = "provisional sample data"
origin_creator = "Brian Bush"
origin_contributors = ["Brian Bush", "Arthur Yip"]
origin_organization = "NREL"
origin_date =  "2021-04-26"
origin_project = "TEMPO"
tags = ["TEMPO"]
data_class = "low"
source = "https://github.nrel.gov/mmurator/TMM/blob/0d89b8f61c624770643a35de1998efe6def5e59c/TEMPO.jl/src/BEV/BEV.jl"
