# --------------------------------------
# TEMPO Dataset Configuration File
# --------------------------------------

dataset_id = "tempo-standard-scenarios-2021"
dataset_type = "sector_model"
model_name = "TEMPO"
path = "/projects/dsgrid/tempo/data"
description = """
CONUS 2022 TEMPO county-level results for BEV charging.""" # TODO: @ayip - don't we have more than BEV here?

origin_creator = "Arthur Yip"
origin_organization = "NREL"
origin_contributors = ["Arthur Yip", "Brian Bush"] # TODO: @ayip add others
origin_project = "" # TODO @ayip
origin_date = "" # TODO @ayip
origin_version = "" # TODO @ayip
source = "https://github.nrel.gov/mmurator/TMM/blob/0d89b8f61c624770643a35de1998efe6def5e59c/TEMPO.jl/src/BEV/BEV.jl" # TODO @ayip
data_classification = "low"
tags = [ "transportation", "conus-2022", "reference", "tempo"]
data_schema_type = "standard" 
trivial_dimensions = [ "sector", "weather_year", "scenario", "data_source"] # TODO: for non-dummy version, we will remove scenario from trivial dimensions

[[dimensions]]
type = "geography"
dimension_id = "" # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]]
type = "subsector"
dimension_id = "" # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]]
type = "metric"
dimension_id = "" # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]]
type = "time"
dimension_id = "" # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]] # TODO: needs a dataset-to-project mapping
type = "model_year"
dimension_id = "" # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]]
type = "data_source"
dimension_id = "" # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]]
type = "sector"
dimension_id = ""  # TODO: The registration process will provide this.
version = "1.0.0"

[[dimensions]]
type = "weather_year"
dimension_id = "2012_weather_year__78aeebf8-788c-4ffa-8df2-f581cf0e4d96"
version = "1.0.0"

# TODO: remove this scenario dimension when we are ready to scrap the dummy dataset
[[dimensions]]
type = "scenario"
dimension_id = "conus-2022-reference__a90f3ea4-b0ed-4c08-a15a-242fb802b156"
version = "1.0.0"

# TODO: uncomment and add registered scenario dimension for final-dataset
# [[dimensions]]
# type = "scenario"
# dimension_id = ""
# version = "1.0.0"

