
# TODO: needs a mapping probably
[[dimensions]]
class = "County"
type = "geography"
name = "ACS County 2018"  #TODO: is this L48 only? 
file = "dimensions/counties.csv"
description = """
American Community Survey US counties, 2018.""" #TODO: is this L48 only? 

[[dimensions]]
class = "Sector"
type = "sector"
name = "Transportation Sector"
file = "dimensions/sector.csv"
description = """Transportation Sector"""


[[dimensions]]
class = "Subsector"
type = "subsector"
name = "TEMPO Bin"
file = "dimensions/bin.csv"
description = """
TEMPO demographic/geographic/vehicle bins.

This is a cross-join of the following supplemental dimensions:
* Composition
* Income
* Urbanity
* Class
* Tech"""


# change this to metric
[[dimensions]]
class = "EnergyEndUse"
type = "metric"
name = "TEMPO LDV BEV Usage" #TODO: Name??
file = "dimensions/end_use.csv"
description = """
Fuels used by TEMPO BEVs.""" # TODO: check these descriptions


[[dimensions]]
class = "Time"
type = "time"
name = "Time of Week by Month"
ranges = [{start = 1, end = 12}]
time_interval_type = "period_ending"
time_type = "representative_period"
measurement_type = "total"
format = "one_week_per_month_by_hour"
description = """
TEMPO Time - Month, day of week, and time of day.""" # TODO: is there a better description for this?


[[dimensions]]
class = "DataSource"
type = "data_source"
name = "TEMPO Model"
file = "dimensions/data_source.csv"
description = """
TEMPO model"""


[[dimensions]]
class = "ModelYear"
type = "model_year"
name = "TEMPO Model Year"
file = "dimensions/year.csv"
description = """
TEMPO modeling years for CONUS 2022 project, 2018-2050"""


# TODO: uncomment this when ready to submit the final dataset
# [[dimensions]]
# class = "Scenario"
# type = "scenario"
# name = "TEMPO Scenario"
# file = "dimensions/scenario.csv"
# description = """
# TEMPO CONUS 2022 scenarios."""