# TODO: needs a mapping probably
[[dimensions]]
class = "County"
type = "geography"
name = "ACS County 2018" 
file = "dimensions/counties.csv"
description = """
American Community Survey US counties, 2018.""" 

[[dimensions]]
class = "Sector"
type = "sector"
name = "Transportation Sector"
file = "dimensions/sector.csv"
description = """Transportation Sector"""


[[dimensions]]
class = "Subsector"
type = "subsector"
name = "TEMPO Bin"
file = "dimensions/bin.csv"
description = """
TEMPO demographic/geographic/vehicle bins.

This is a cross-join of the following supplemental dimensions:
* Composition (Single Driver, Some Drivers Smaller, Some Drivers Larger)
* Income (Low Income, Middle Income, High Income)
* Urbanity (Rural, Small Town, Suburban, Second City, Urban)
* Vehicle Size Class (Compact, Midsize, SUV, Pickup)
* Tech (PHEV25/PHEV50/BEV100/BEV300) """



[[dimensions]]
class = "EnergyEndUse"
type = "metric"
name = "TEMPO LDV PEV Usage"
file = "dimensions/end_use.csv"
description = """
Type of charging (L1 and L2, DCFC) used by TEMPO PEVs."""


[[dimensions]]
class = "Time"
type = "time"
name = "Time of Week by Month"
ranges = [{start = 1, end = 12}]
time_interval_type = "period_ending"
time_type = "representative_period"
measurement_type = "total"
format = "one_week_per_month_by_hour"
description = """
TEMPO Time - Month (representing seasons), day of week, and hour of day."""


[[dimensions]]
class = "DataSource"
type = "data_source"
name = "TEMPO Model"
file = "dimensions/data_source.csv"
description = """
TEMPO model"""


[[dimensions]]
class = "ModelYear"
type = "model_year"
name = "TEMPO Model Year"
file = "dimensions/year.csv"
description = """
TEMPO modeling years for CONUS 2022 project, 2018-2050"""

[[dimensions]]
class = "Scenario"
type = "scenario"
name = "LDV Sales All-EV by 2035" 
file = "dimensions/scenario.csv"
description = """
LDV Sales All-EV by 2035""" 
