

[[dimensions]]
type = "geography"
name = "County"
file = "../../../dimensions/counties.csv" #FIXME: What is the vintage of TEMPO counties?
description = """
US counties.
"""

[[dimensions]]
type = "sector"
name = "TEMPO LDV BEV Charging"
file = "dimensions/tempo.csv"
description = """
TEMPO provides LDV BEV charging profiles.
"""
trivial = true

[[dimensions]]
type = "subsector"
name = "TEMPO Bin"
file = "dimensions/bin.csv"
description = """
TEMPO demographic/geographic/vehicle bins.

This is a cross-join of the following supplemental dimensions:
* Composition
* Income
* Urbanity
* Class
* Tech
"""

[[dimensions]]
type = "subsector"
name = "Composition"
file = "dimensions/supplemental/composition.csv"
description = """
Household composition.
"""

[[dimensions]]
type = "subsector"
name = "Income"
file = "dimensions/supplemental/income.csv"
description = """
Income range.
"""

[[dimensions]]
type = "subsector"
name = "Urbanity"
file = "dimensions/supplemental/urbanity.csv"
description = """
Urban classifications, according to [Claritas definitions](https://healthpolicy.ucla.edu/chis/data/public-use-data-file/Documents/2003PUF_constructs_c.pdf#page=24).
"""

[[dimensions]]
type = "subsector"
name = "Class"
file = "dimensions/supplemental/class.csv"
description = """
Passenger vehicle class.
"""

[[dimensions]]
type = "subsector"
name = "Tech"
file = "dimensions/supplemental/tech.csv"
description = """
Vehicle technology.
"""

[[dimensions]]
type = "end_use"
name = "TEMPO LDV BEV Usage"
file = "dimensions/end_use.csv"
description = """
Fuels used by TEMPO BEVs.
"""

[[dimensions]]
type = "time"
name = "Time of Week, by Month"
start = "Jan Mon 00:00:00"
end = "Dec Sun 23:59:59"
frequence = "1 second"
includes_dst = false
period = "period_ending"
str_format = "%a %w %X"
timezone = "LOCAL"
value_representation = "sum"
description = """
Month, day of week, and time of day.
"""

[[dimensions]]
type = "data_source"
name = "TEMPO Model"
file = "dimensions/model.csv"
description = """
Weather year used by TEMPO.
"""
trivial = true

[[dimensions]]
type = "model_year"
name = "TEMPO Model Year"
file = "dimensions/year.csv"
description = """
TEMPO modeling years.
"""

[[dimensions]]
type = "scenario"
name = "TEMPO Scenario"
file = "dimensions/scenario.csv"
description = """
TEMPO base scenario only.
"""
trivial = true

[[dimensions]]
type = "weather_year"
name = "TEMPO Weather Year"
file = "dimensions/weather.csv"
description = """
Weather year used by TEMPO.
"""
trivial = true
