[[mappings]]
description = "ACS County 2018 to ACS County 2020 L48"
file = "dimension_mappings/county_to_county.csv"
dimension_type = "geography"

[[mappings]]
description = "TEMPO CONUS 2022 End Uses to dsgrid CONUS 2022 End Uses w/ all units in kWh"
dimension_type = "metric"
file = "dimension_mappings/metric_to_metric.csv"
mapping_type = "one_to_one"

[[mappings]]
description = "2018-2050 from interpolating for every other year"
dimension_type = "model_year"
file = "dimension_mappings/model_year_to_model_year.csv"
mapping_type = "many_to_many"

[[mappings]]
description = "TEMPO demographic/geographic/vehicle bins (CONUS 2022) to dsgrid CONUS 2022 Subsectors"
dimension_type = "subsector"
file = "dimension_mappings/subsector_to_subsector.csv"
mapping_type = "many_to_one_aggregation"

[[mappings]]
description = "rename TEMPO scenarios to CONUS 2022 scenarios"
dimension_type = "scenario"
file = "dimension_mappings/scenario_to_scenario.csv"
mapping_type = "one_to_one"
