# ------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------
[[dimensions]]
class = "Geography"
description = """United States, excluding territories"""
file = "dimensions/geography_united_states_excluding_territories.csv"
module = "dsgrid.dimension.standard"
name = "United States Excluding Territories"
type = "geography"

[[dimensions]]
class = "Sector"
description = """commercial sector only"""
file = "dimensions/sector_commercial.csv"
module = "dsgrid.dimension.standard"
name = "Commercial"
type = "sector"

[[dimensions]]
class = "SubSector"
description = """all subsectors combined"""
file = "dimensions/subsector_all_subsectors_combined.csv"
module = "dsgrid.dimension.standard"
name = "All Subsectors Combined"
type = "subsector"

[[dimensions]]
class = "EndUse"
description = """EIA AEO electricity demand and loss: commercial end uses (valid for AEO 2018-2020)
"""
file = "dimensions/eia_aeo_commercial_enduses_valid_2018_to_2020.csv"
module = "dsgrid.dimension.standard"
name = "AEO Commercial End Uses-Valid 2018-2020"
type = "end_use"

[[dimensions]]
class = "WeatherYear"
description = """
EIA AEO weather years: 2016 - 2050
"""
file = "dimensions/weather_years_2016_to_2050.csv"
module = "dsgrid.dimension.standard"
name = "AEO Weather Years 2016-2050"
type = "weather_year"

[[dimensions]]
class = "ModelYear"
description = """
EIA AEO model years: 2016 - 2050
"""
file = "dimensions/model_years_2016_to_2050.csv"
module = "dsgrid.dimension.standard"
name = "AEO Model Years 2016-2050"
type = "model_year"

[[dimensions]]
class = "Scenario"
description = """
EIA AEO reference scenario
"""
file = "dimensions/scenario_eia_aeo_reference.csv"
module = "dsgrid.dimension.standard"
name = "AEO Reference"
type = "scenario"

[[dimensions]]
class = "DataSource"
description = """
EIA AEO 2018 electricity demand projection
"""
file = "dimensions/data_source_eia_aeo_2018.csv"
module = "dsgrid.dimension.standard"
name = "AEO 2018"
type = "data_source"

[[dimensions]]
class = "Time"
description = """
Time dimension, 2016 - 2050, annual
"""
end = "2050"
frequency = "1 year"
includes_dst = false
name = "time-2016-2050-annual"
period = "period_beginning"
start = "2016"
str_format = "%Y"
timezone = "UTC" #none
type = "time"
value_representation = "total"

