data_source = "AEO2021 Reference Case"
dataset_id = "aeo2021_ref_res_stock_growth_factors"
data_schema_type = "standard"
dataset_type = "sector_model" # <--- benchmark?
path = "s3://nrel-dsgrid-registry/data/benchmark/aeo2021/aeo2021_ref_res_stock_growth_factors/1.0.0" # <---
description = "AEO 2021 Reference Case Residential Stock (bldg unit and sqft) Annual Growth Factors, for ResStock"
origin_creator = "Lixi Liu"
origin_organization = "NREL"
origin_contributors = [ "Lixi Liu", "Noah Sandoval", "Anthony Fortanini", "Meghan Mooney", "Elaine Hale",]
origin_project = "Energy Benchmarking and Projection" # <---
origin_date = "2021-10-05"
origin_version = "0.1.0"
source = "Data derived from AEO 2021 detailed sector files sent from EIA"
data_classification = "low"
tags = [ "residential", "benchmark", "projection", "aeo", "2021", "dsgrid_v0.2.0",]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
dimension_id = "" # <---
type = "geography"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "sector"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "subsector"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "metric"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "weather_year"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "model_year"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "scenario"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "data_source"
version = "1.0.0"

[[dimensions]]
dimension_id = "" # <---
type = "time"
version = "1.0.0"

