# ------------------------------------------------
# AEO 2021 Reference Case - Commercial End Use Growth Factors
# ------------------------------------------------

dataset_id = "aeo2021_reference_commercial_energy_use_growth_factors"
dataset_type = "modeled"
data_source = "NEMS Commercial Module"
description = """
AEO 2021 Reference Case Commercial Energy End Use Annual Growth Factors. 
Derived by NREL as simple exponential growth rates from annual end use comsumptions between year 2018 and year 2050. 
Detailed end use consumption data provided by EIA, not available in API.
"""

origin_creator = "Kevin Jarzomski"
origin_organization = "EIA"
origin_contributors = [ "Lixi Liu"]
origin_project = "dsgrid CONUS2022 Commercial Buildings Projection"
origin_date = "2021-10-05"
origin_version = "0.1.0"
source = "Data derived from AEO 2021 detailed commercial sector files sent from EIA"
data_classification = "low"
tags = [ "commercial", "benchmark", "projection", "aeo2021", "dsgrid_v0.2.0",]
trivial_dimensions = [ "sector", "scenario", "data_source", "weather_year", "model_year"]

data_schema_type = "one_table"
dataset_qualifier = "growth_rate"

[data_schema]
load_data_column_dimension = "metric"

[dataset_qualifier_metadata]
growth_rate_type = "exponential_annual"

##### Dimensions #####

[[dimensions]]
class = "CensusDivision"
description = """
US Census Divisions
"""
file = "../../../../../dimensions/supplemental/census_divisions.csv"
module = "dsgrid.dimension.standard"
name = "US Census Divisions"
type = "geography"
display_name = "Census Division"

[[dimensions]]
class = "Sector"
description = """
Commercial sector only
"""
file = "../../../../modeled/comstock/dimensions/sector_commercial.csv"
module = "dsgrid.dimension.standard"
name = "commercial-sector"
type = "sector"
display_name = "Commercial"

[[dimensions]]
class = "Subsector"
description = """
AEO 2021 commercial building types (N=11)
"""
file = "dimensions/aeo2021_commercial_building_types.csv"
module = "dsgrid.dimension.standard"
name = "AEO2021-commercial-building-types"
display_name = "Commercial Subsector"
type = "subsector"

[[dimensions]]
class = "EnergyEndUse"
description = """
AEO 2021 commercial energy end uses (unitless) for growth rates (N=19, from 10 end uses, 3 fuel types)
"""
file = "dimensions/aeo2021_commercial_energy_enduses.csv"
module = "dsgrid.dimension.standard"
name = "AEO2021-commercial-energy-enduses-unitless"
type = "metric"
display_name = "AEO Commercial End Uses"

[[dimensions]]
class = "Scenario"
description = """
EIA AEO Reference Scenario
"""
file = "dimensions/aeo_reference_scenario.csv"
module = "dsgrid.dimension.standard"
name = "AEO-Reference-Scenario"
type = "scenario"
display_name = "AEO Reference Scenario"

[[dimensions]]
class = "DataSource"
description = """
EIA Annual Energy Outlook (AEO) 2021
"""
file = "dimensions/sources.csv"
module = "dsgrid.dimension.standard"
name = "Data-Source-AEO-2021"
type = "data_source"
display_name = "Data-Source-AEO-2021"

[[dimensions]]
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "../../../../../dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
display_name = "Weather 2012"
type = "weather_year"

[[dimensions]]
class = "ModelYear"
description = """
Model years, 2013-2050, trivial, single record
"""
file = "dimensions/model_years_trivial_2013_to_2050.csv"
module = "dsgrid.dimension.standard"
name = "Model_Years-trivial-2013_to_2050"
type = "model_year"
display_name = "AEO Model Years"

[[dimensions]]
class = "NoOpTime"
description = "No Operation Time"
time_type = "noop"
module = "dsgrid.dimension.standard"
name = "noop_time"
type = "time"
display_name = "No Op Time"
