[[mappings]]
dimension_type = "subsector"
description = "Maps Baseline ComStock building types to AEO 2021 commercial building types"
file = "dimension_mappings/lookup_comstock_to_aeo2021_com_bldg_types.csv"
mapping_type = "many_to_many_assignment"

[[mappings]]
dimension_type = "metric"
description = "Maps Baseline ComStock end uses to AEO 2021 commercial end uses"
file = "dimension_mappings/lookup_comstock_to_aeo2021_com_enduses.csv"
mapping_type = "many_to_many_assignment"

[[mappings]]
description = "AEO2021-residential model year dimension mapping for the CONUS 2022 project"
dimension_type = "model_year"
file = "../../residential/End_Use_Growth_Factors/dimension_mappings/model_year_to_model_year.csv"
mapping_type = "duplication"

[[mappings]]
dimension_type = "scenario"
description = "Maps AEO 2021 scenarios to project scenarios"
file = "dimension_mappings/scenario_to_scenario.csv"
mapping_type = "duplication"
