# ------------------------------------------------------
# Dataset Dimensions
# ------------------------------------------------------
# [[dimensions]]
# name = "US Census Division"
# type = "geography"

# [[dimensions]]
# name = "Res Com Ind Trans Sectors"
# type = "sector"

# [[dimensions]]
# name = "All Subsectors Combined"
# type = "subsector"

# [[dimensions]]
# name = "All End Uses Combined"
# type = "end_use"

# [[dimensions]]
# name = "EIA AEO Weather Years 2019-2050"
# type = "weather_year"

# [[dimensions]]
# name = "EIA AEO Model Years 2019-2050"
# type = "model_year"

# [[dimensions]]
# name = "EIA AEO Reference"
# type = "scenario"

# [[dimensions]]
# name = "EIA AEO 2020"
# type = "data_source"

# [[dimensions]]
# name = "time-2019-2050-annual"
# type = "time"
