# --------------------------------------
# ComStock Dataset Configuration File
# --------------------------------------

dataset_id = "conus_2022_reference_comstock"
dataset_type = "sector_model"
data_source = "ComStock"

path = "/Users/lliu2/Downloads/end_use_time_wrapped_com_downcasted"
description = """
Simulated on 09/29/2021 using: 
Comstock SHA: 00a3f79bab74d7fb8b71e7897486eb54b51277fc and
buildstock SHA: 9e00b5649c96ad18bc6336ba9b24c81156f8fd2d

Post-processed using AWS ightGlass and notebooks from https://github.com/NREL/SightGlassDataProcessing/tree/agg_for_dsgrid
"""

origin_creator = "Lixi Liu"
origin_organization = "NREL"
origin_contributors = ["Marlena Praprost", "Lixi Liu", "Andrew Parker"]
origin_project = "End Use Load Profiles"
origin_date = "2021-09-29"
origin_version = "0.1.0"
source = "s3://eulp/simulation_output/regional_runs/comstock/com_dsgrid_full_2/com_dsgrid_full_2/"
data_classification = "low"
tags = [ "commercial", "conus-2022", "reference", "dsgrid_v0.2.0", "standard_scenarios"]
data_schema_type = "standard"
trivial_dimensions = ["sector", "weather_year", "model_year", "scenario", "data_source"]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
type = "geography"
dimension_id = "conus_2022-comstock_us_county_fip__1665d121-bd0f-4278-8420-c1a4e61fe774"
version = "1.0.0"

[[dimensions]]
type = "sector"
dimension_id = "commercial-sector__e9ccef84-0aed-4b7f-b682-e2604f16b511"
version = "1.0.0"

[[dimensions]]
type = "subsector"
dimension_id = "conus_2022-comstock_building_types__9d67aca5-fdbf-4ac8-8086-f1da6547d807"
version = "1.0.0"

[[dimensions]]
type = "metric"
dimension_id = "conus_2022-comstock_energy_enduses_kwh__f420cf50-6ac1-42c4-8cd4-c73299c25814"
version = "1.0.0"

[[dimensions]]
type = "data_source"
dimension_id = "comstock_data_source__2ecde85e-5896-43b5-95ce-725bdd2f40a0"
version = "1.0.0"

[[dimensions]]
type = "scenario"
dimension_id = "conus-2022-reference__a90f3ea4-b0ed-4c08-a15a-242fb802b156"
version = "1.0.0"

[[dimensions]]
type = "weather_year"
dimension_id = "2012_weather_year__78aeebf8-788c-4ffa-8df2-f581cf0e4d96"
version = "1.0.0"

[[dimensions]]
type = "model_year"
dimension_id = "model-year-2018__055f9044-b09b-4372-830c-b6f08dd7ecc1"
version = "1.0.0"

[[dimensions]] # time-wrapped data
type = "time"
dimension_id = "time-2012-utc-8784-hourly-periodending-total-hour0start__8ae089c3-733c-4db8-92a0-01f01db49cbd"
version = "1.0.0"


