# --------------------------------------
# ComStock Dataset Configuration File
# --------------------------------------

dataset_id = "conus_2022_reference_comstock"
dataset_type = "sector_model"
data_source = "comstock"
description = """
Time-shifted and filled for Dec31, simulated on 09/29/2021 using:
Comstock SHA: 00a3f79bab74d7fb8b71e7897486eb54b51277fc and
buildstock SHA: 9e00b5649c96ad18bc6336ba9b24c81156f8fd2d
(Post-processed using AWS SightGlass and notebooks from https://github.com/NREL/SightGlassDataProcessing/tree/agg_for_dsgrid)
"""

origin_creator = "Lixi Liu"
origin_organization = "NREL"
origin_contributors = ["Marlena Praprost", "Lixi Liu", "Andrew Parker"]
origin_project = "End Use Load Profiles"
origin_date = "2021-09-29"
origin_version = "0.1.0"
source = "s3://eulp/simulation_output/regional_runs/comstock/com_dsgrid_full_2/com_dsgrid_full_2/"
data_classification = "low"
tags = ["commercial", "conus-2022", "reference", "dsgrid_v0.2.0", "standard_scenarios"]
data_schema_type = "standard"
trivial_dimensions = ["sector", "weather_year", "model_year", "scenario", "data_source"]

[data_schema]
load_data_column_dimension = "metric"

[[dimensions]]
type = "geography"
name = "conus_2022-comstock_US_county_FIP"
display_name = "County"
file = "dimensions/conus_2022-comstock_geography_county_fips.csv"
module = "dsgrid.dimension.standard"
class = "County"
description = """
CONUS 2022 - ComStock US county in (older version) original FIP code (N=3,133),
includes 23 AK counties, 1 county renamed in 2015 (SD, Shannon County -> SD, Oglala Lakota County),
1 city (VA, Bedford City) that is now part of a county (VA Bedford County).
"""

[[dimensions]]
type = "sector"
name = "commercial-sector"
display_name = "Commercial"
file = "dimensions/sector_commercial.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Commercial sector only
"""

[[dimensions]]
type = "subsector"
name = "conus_2022-comstock_building_types"
display_name = "ComStock Building Type"
file = "dimensions/conus_2022-comstock_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = """
CONUS 2022 - ComStock building types (N=14)
"""

[[dimensions]]
type = "metric"
name = "conus_2022-comstock_energy_enduses_kwh"
display_name = "ComStock End Use"
file = "dimensions/conus_2022-comstock_end_uses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
CONUS 2022 - ComStock end uses (N=21, 4 fuel types)
"""

[[dimensions]]
type = "scenario"
name = "Conus-2022"
display_name = "Reference"
file = "../resstock/dimensions/scenario_conus_2022_reference.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
Scenario: CONUS (Continental U.S.) 2022 Reference
"""

[[dimensions]]
type = "data_source"
name = "Comstock-Data-Source"
display_name = "ComStock"
file = "dimensions/data_source_comstock.csv"
module = "dsgrid.dimension.standard"
class = "DataSource"
description = """
Data source: ComStock
"""

[[dimensions]]
type = "model_year"
name = "Model-Year-2018"
display_name = "Model Year 2018"
file = "../resstock/dimensions/model_year_2018.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model year: 2018
"""

[[dimensions]] # shared with project
class = "WeatherYear"
description = """
Weather year, 2012 only
"""
file = "../../../dimensions/weather_years.csv"
module = "dsgrid.dimension.standard"
name = "2012 Weather Year"
display_name = "Weather 2012"
type = "weather_year"

# [[dimensions]] # for real dataset
# name = "Time-2012-UTC-8784-hourly-periodEnding-total-Hour6Start-localRangesTZ"
# display_name = "Timestamp"
# type = "time"
# module = "dsgrid.dimension.standard"
# class = "Time"
# description = "Time dimension, 2012 hourly UTC, period-ending, starts at Hour 6, 8784 timestamps, total value, local ranges_timezone"
# time_type = "datetime"
# measurement_type = "total"
# str_format = "%Y-%m-%d %H:%M:%S"
# frequency = "P0DT1H0M0.000000S"
# leap_day_adjustment = "none"
# time_interval_type = "period_ending"
# timezone = "UTC"
# ranges = [{start = "2012-01-01 01:00:00", end = "2013-01-01 00:00:00"}]
# ranges_timezone = "LOCAL"

[[dimensions]] # for time-wrapped dataset
class = "Time"
frequency = "P0DT1H0M0.000000S"
name = "Time-2012-EST-8784-hourly-periodEnding-noLeapDayAdjustment-total-Hour0Start"
display_name = "Time EST"
ranges = [{start = "2012-01-01 00:00:00", end = "2012-12-31 23:00:00"}]
time_type = "datetime"
leap_day_adjustment = "none"
description = """
Time dimension, 2012 hourly EST, hour-ending, no Leap Day Adjustment, total value, starts at Hour 0
"""
time_interval_type = "period_ending"
str_format = "%Y-%m-%d %H:%M:%S"
timezone = "EasternStandard"
measurement_type = "total"
type = "time"
