# ------------------------------------------------------
# ComStock AMY2012 MY2018 Conus 2022
# ------------------------------------------------------
[[dimensions]]
type = "geography"
name = "conus_2022-comstock_US_county_FIP"
file = "dimensions/conus_2022-comstock_geography.csv"
module = "dsgrid.dimension.standard"
class = "County"
description = """
CONUS 2022 - ComStock US county in original FIP code (N=3,060), ComStock not in 48 counties.
"""

[[dimensions]]
type = "sector"
name = "commercial-sector"
file = "dimensions/sector_commercial.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Commercial sector only
"""

[[dimensions]]
type = "subsector"
name = "conus_2022-comstock_building_types"
file = "dimensions/conus_2022-comstock_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "Subsector"
description = """
CONUS 2022 - ComStock building types (N=14)
"""

[[dimensions]]
type = "metric"
name = "conus_2022-comstock_energy_enduses_kwh"
file = "dimensions/conus_2022-comstock_end_uses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
CONUS 2022 - ComStock end uses (N=21, 4 fuel types)
"""

# [[dimensions]] # already exists
# type = "scenario"
# name = "Conus-2022"
# file = "dimensions/scenario_conus_2022_reference.csv"
# module = "dsgrid.dimension.standard"
# class = "Scenario"
# description = """
# Scenario: CONUS (Continental U.S.) 2022 Reference
# """

# [[dimensions]] # already exists
# type = "data_source"
# name = "Data-Source-comstock"
# file = "dimensions/data_source_comstock.csv"
# module = "dsgrid.dimension.standard"
# class = "Model"
# description = """
# Data source: ComStock
# """

# [[dimensions]] # already exists
# type = "weather"
# name = "AMY-2012"
# file = "dimensions/weather_year_2012.csv"
# module = "dsgrid.dimension.standard"
# class = "Weather"
# description = """
# Weather year: AMY 2012
# """

# [[dimensions]] # already exists
# type = "model_year"
# name = "Model-Year-2018"
# file = "dimensions/model_year_2018.csv"
# module = "dsgrid.dimension.standard"
# class = "ModelYear"
# description = """
# Model year: 2018
# """

[[dimensions]] # FIXME
name = "Time-2012-UTC-8760-hourly-periodEnding-dropDec31-total-Hour5Start"
type = "time"
module = "dsgrid.dimension.standard"
class = "Time"
description = "Time dimension, 2012 hourly UTC, period-ending, starts at Hour 5, 8760 timestamps, drop Dec 31, total value"
time_type = "datetime"
measurement_type = "total"
str_format = "%Y-%m-%d %H:%M:%S"
frequency = "P0DT1H0M0.000000S"
leap_day_adjustment = "drop_dec31"
time_interval_type = "period_ending"
timezone = "UTC"
ranges = [{start = "2012-01-01 05:00:00", end = "2012-12-31 09:00:00"}] # FIXME


