# ------------------------------------------------------
# ComStock WY2012 MY2018 Standard Scenarios
# ------------------------------------------------------
[[dimensions]]
type = "geography"
name = "US-county-FIP"
file = "dimensions/comstock_geography_orig_fip_tentative.csv"
module = "dsgrid.dimension.standard"
description = """
US county in original FIP code
"""

[[dimensions]] # FIXME trivial?
type = "sector"
name = "commercial-sector"
file = "dimensions/xx.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Commercial sector
"""

[[dimensions]]
type = "subsector"
name = "comstock-building-types"
file = "dimensions/comstock_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "SubSector"
description = """
Comstock building types
"""

[[dimensions]]
type = "metric"
name = "comstock-energy-enduses"
file = "dimensions/comstock_end_uses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
Comstock end uses, available from ComStock timeseries results, not annual result summary.
"""

[[dimensions]] # FIXME
type = "scenario"
name = "AEO-Reference-Scenario"
file = "dimensions/xxx.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
AEO Reference Scenario
"""

[[dimensions]] # FIXME # SHOW WE PUT SHA HERE? or in the dataset.toml
type = "data_source"
name = "Data-Source-comstock-2021"
file = "dimensions/xxx.csv"
module = "dsgrid.dimension.standard"
class = "Model"
description = """
ComStock, SHA: xxx
"""

[[dimensions]]
type = "weather"
name = "AMY-2012"
file = "dimensions/weather_year_2012.csv"
module = "dsgrid.dimension.standard"
class = "Weather"
description = """
Weather year - AMY 2012
"""

[[dimensions]]
type = "model_year"
name = "Model-Year-2018"
file = "dimensions/model_year_2018.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model year 2018
"""

[[dimensions]] # CHECK/FIX ME
class = "Time"
description = """Time 2012 UTC"""
module = "dsgrid.dimension.standard"
name = "Time-UTC-2012"
measurement_type = "total"
include_leap_day = true
type = "time"
time_type = "hourly"


