# ------------------------------------------------------
# ComStock WY2012 MY2018 Standard Scenarios
# ------------------------------------------------------
[[dimensions]]
type = "geography"
name = "standard_scenarios-comstock_US_county_FIP"
file = "dimensions/standard_scenarios_comstock_geography.csv"
module = "dsgrid.dimension.standard"
description = """
Standard Scenarios - ComStock US county in original FIP code (N=3,060), ComStock not in 48 counties.
"""

[[dimensions]] # FIXME trivial?
type = "sector"
name = "commercial-sector"
file = "dimensions/xx.csv"
module = "dsgrid.dimension.standard"
class = "Sector"
description = """
Commercial sector
"""

[[dimensions]]
type = "subsector"
name = "standard_scenarios-comstock_building_types"
file = "dimensions/standard_scenarios_comstock_subsectors.csv"
module = "dsgrid.dimension.standard"
class = "SubSector"
description = """
Standard Scenarios - Comstock building types
"""

[[dimensions]]
type = "metric"
name = "standard_scenarios-comstock_energy_enduses"
file = "dimensions/standard_scenarios_comstock_end_uses.csv"
module = "dsgrid.dimension.standard"
class = "EnergyEndUse"
description = """
Standard Scenarios - Comstock end uses
"""

[[dimensions]] # FIXME
type = "scenario"
name = "Standard-Scenarios"
file = "dimensions/xxx.csv"
module = "dsgrid.dimension.standard"
class = "Scenario"
description = """
Standard Scenarios
"""

[[dimensions]] # FIXME # SHOW WE PUT SHA HERE? or in the dataset.toml
type = "data_source"
name = "Data-Source-comstock-2021"
file = "dimensions/standard_scenarios_comstock_data_source.csv"
module = "dsgrid.dimension.standard"
class = "Model"
description = """
Comstock SHA: 00a3f79bab74d7fb8b71e7897486eb54b51277fc |
buildstock SHA: 9e00b5649c96ad18bc6336ba9b24c81156f8fd2d
Simulated on 09/29/2021
"""

[[dimensions]]
type = "weather"
name = "AMY-2012"
file = "dimensions/weather_year_2012.csv"
module = "dsgrid.dimension.standard"
class = "Weather"
description = """
Weather year - AMY 2012
"""

[[dimensions]]
type = "model_year"
name = "Model-Year-2018"
file = "dimensions/model_year_2018.csv"
module = "dsgrid.dimension.standard"
class = "ModelYear"
description = """
Model year 2018
"""

[[dimensions]] # CHECK/FIX ME
class = "Time"
description = """Time 2012 UTC"""
module = "dsgrid.dimension.standard"
name = "Time-UTC-2012"
measurement_type = "total"
include_leap_day = true
type = "time"
time_type = "hourly"


